// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: tilder/v1/fs.proto

// Files over the `fs` DataChannel (ADR 0022). Paths and names are bytes: the
// exact names on disk, never normalised, maybe not UTF-8. A path is
// slash-separated and relative to the machine's home; empty is the home.
// Every message carries its request's id; replies carry the same id.

package tilderv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FsKind int32

const (
	FsKind_FS_KIND_UNSPECIFIED FsKind = 0
	FsKind_FS_KIND_FILE        FsKind = 1
	FsKind_FS_KIND_DIR         FsKind = 2
	FsKind_FS_KIND_SYMLINK     FsKind = 3
	FsKind_FS_KIND_OTHER       FsKind = 4
)

// Enum value maps for FsKind.
var (
	FsKind_name = map[int32]string{
		0: "FS_KIND_UNSPECIFIED",
		1: "FS_KIND_FILE",
		2: "FS_KIND_DIR",
		3: "FS_KIND_SYMLINK",
		4: "FS_KIND_OTHER",
	}
	FsKind_value = map[string]int32{
		"FS_KIND_UNSPECIFIED": 0,
		"FS_KIND_FILE":        1,
		"FS_KIND_DIR":         2,
		"FS_KIND_SYMLINK":     3,
		"FS_KIND_OTHER":       4,
	}
)

func (x FsKind) Enum() *FsKind {
	p := new(FsKind)
	*p = x
	return p
}

func (x FsKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FsKind) Descriptor() protoreflect.EnumDescriptor {
	return file_tilder_v1_fs_proto_enumTypes[0].Descriptor()
}

func (FsKind) Type() protoreflect.EnumType {
	return &file_tilder_v1_fs_proto_enumTypes[0]
}

func (x FsKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FsKind.Descriptor instead.
func (FsKind) EnumDescriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{0}
}

type FsError_Code int32

const (
	FsError_CODE_UNSPECIFIED FsError_Code = 0
	FsError_CODE_DENIED      FsError_Code = 1
	FsError_CODE_NOT_FOUND   FsError_Code = 2
	FsError_CODE_EXISTS      FsError_Code = 3
	FsError_CODE_NOT_DIR     FsError_Code = 4
	FsError_CODE_IS_DIR      FsError_Code = 5
	FsError_CODE_NOT_REGULAR FsError_Code = 6
	FsError_CODE_CONFLICT    FsError_Code = 7
	FsError_CODE_INVALID     FsError_Code = 8
	FsError_CODE_NO_SPACE    FsError_Code = 9
	FsError_CODE_BUSY        FsError_Code = 10 // too many requests at once on this channel
	FsError_CODE_WATCH_LIMIT FsError_Code = 11 // cannot watch it: the console looks again on focus instead
)

// Enum value maps for FsError_Code.
var (
	FsError_Code_name = map[int32]string{
		0:  "CODE_UNSPECIFIED",
		1:  "CODE_DENIED",
		2:  "CODE_NOT_FOUND",
		3:  "CODE_EXISTS",
		4:  "CODE_NOT_DIR",
		5:  "CODE_IS_DIR",
		6:  "CODE_NOT_REGULAR",
		7:  "CODE_CONFLICT",
		8:  "CODE_INVALID",
		9:  "CODE_NO_SPACE",
		10: "CODE_BUSY",
		11: "CODE_WATCH_LIMIT",
	}
	FsError_Code_value = map[string]int32{
		"CODE_UNSPECIFIED": 0,
		"CODE_DENIED":      1,
		"CODE_NOT_FOUND":   2,
		"CODE_EXISTS":      3,
		"CODE_NOT_DIR":     4,
		"CODE_IS_DIR":      5,
		"CODE_NOT_REGULAR": 6,
		"CODE_CONFLICT":    7,
		"CODE_INVALID":     8,
		"CODE_NO_SPACE":    9,
		"CODE_BUSY":        10,
		"CODE_WATCH_LIMIT": 11,
	}
)

func (x FsError_Code) Enum() *FsError_Code {
	p := new(FsError_Code)
	*p = x
	return p
}

func (x FsError_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FsError_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_tilder_v1_fs_proto_enumTypes[1].Descriptor()
}

func (FsError_Code) Type() protoreflect.EnumType {
	return &file_tilder_v1_fs_proto_enumTypes[1]
}

func (x FsError_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FsError_Code.Descriptor instead.
func (FsError_Code) EnumDescriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{23, 0}
}

type FsClient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	ReqId uint32                 `protobuf:"varint,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*FsClient_Stat
	//	*FsClient_List
	//	*FsClient_Read
	//	*FsClient_Ack
	//	*FsClient_Write
	//	*FsClient_Data
	//	*FsClient_Commit
	//	*FsClient_Abort
	//	*FsClient_Mkdir
	//	*FsClient_Rename
	//	*FsClient_Remove
	//	*FsClient_Cancel
	//	*FsClient_Watch
	//	*FsClient_Unwatch
	Msg           isFsClient_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsClient) Reset() {
	*x = FsClient{}
	mi := &file_tilder_v1_fs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsClient) ProtoMessage() {}

func (x *FsClient) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_fs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsClient.ProtoReflect.Descriptor instead.
func (*FsClient) Descriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{0}
}

func (x *FsClient) GetReqId() uint32 {
	if x != nil {
		return x.ReqId
	}
	return 0
}

func (x *FsClient) GetMsg() isFsClient_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *FsClient) GetStat() *FsStat {
	if x != nil {
		if x, ok := x.Msg.(*FsClient_Stat); ok {
			return x.Stat
		}
	}
	return nil
}

func (x *FsClient) GetList() *FsList {
	if x != nil {
		if x, ok := x.Msg.(*FsClient_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *FsClient) GetRead() *FsRead {
	if x != nil {
		if x, ok := x.Msg.(*FsClient_Read); ok {
			return x.Read
		}
	}
	return nil
}

func (x *FsClient) GetAck() *FsAck {
	if x != nil {
		if x, ok := x.Msg.(*FsClient_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *FsClient) GetWrite() *FsWrite {
	if x != nil {
		if x, ok := x.Msg.(*FsClient_Write); ok {
			return x.Write
		}
	}
	return nil
}

func (x *FsClient) GetData() *FsData {
	if x != nil {
		if x, ok := x.Msg.(*FsClient_Data); ok {
			return x.Data
		}
	}
	return nil
}

func (x *FsClient) GetCommit() *FsCommit {
	if x != nil {
		if x, ok := x.Msg.(*FsClient_Commit); ok {
			return x.Commit
		}
	}
	return nil
}

func (x *FsClient) GetAbort() *FsAbort {
	if x != nil {
		if x, ok := x.Msg.(*FsClient_Abort); ok {
			return x.Abort
		}
	}
	return nil
}

func (x *FsClient) GetMkdir() *FsMkdir {
	if x != nil {
		if x, ok := x.Msg.(*FsClient_Mkdir); ok {
			return x.Mkdir
		}
	}
	return nil
}

func (x *FsClient) GetRename() *FsRename {
	if x != nil {
		if x, ok := x.Msg.(*FsClient_Rename); ok {
			return x.Rename
		}
	}
	return nil
}

func (x *FsClient) GetRemove() *FsRemove {
	if x != nil {
		if x, ok := x.Msg.(*FsClient_Remove); ok {
			return x.Remove
		}
	}
	return nil
}

func (x *FsClient) GetCancel() *FsCancel {
	if x != nil {
		if x, ok := x.Msg.(*FsClient_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

func (x *FsClient) GetWatch() *FsWatch {
	if x != nil {
		if x, ok := x.Msg.(*FsClient_Watch); ok {
			return x.Watch
		}
	}
	return nil
}

func (x *FsClient) GetUnwatch() *FsUnwatch {
	if x != nil {
		if x, ok := x.Msg.(*FsClient_Unwatch); ok {
			return x.Unwatch
		}
	}
	return nil
}

type isFsClient_Msg interface {
	isFsClient_Msg()
}

type FsClient_Stat struct {
	Stat *FsStat `protobuf:"bytes,2,opt,name=stat,proto3,oneof"`
}

type FsClient_List struct {
	List *FsList `protobuf:"bytes,3,opt,name=list,proto3,oneof"`
}

type FsClient_Read struct {
	Read *FsRead `protobuf:"bytes,4,opt,name=read,proto3,oneof"`
}

type FsClient_Ack struct {
	Ack *FsAck `protobuf:"bytes,5,opt,name=ack,proto3,oneof"`
}

type FsClient_Write struct {
	Write *FsWrite `protobuf:"bytes,6,opt,name=write,proto3,oneof"`
}

type FsClient_Data struct {
	Data *FsData `protobuf:"bytes,7,opt,name=data,proto3,oneof"`
}

type FsClient_Commit struct {
	Commit *FsCommit `protobuf:"bytes,8,opt,name=commit,proto3,oneof"`
}

type FsClient_Abort struct {
	Abort *FsAbort `protobuf:"bytes,9,opt,name=abort,proto3,oneof"`
}

type FsClient_Mkdir struct {
	Mkdir *FsMkdir `protobuf:"bytes,10,opt,name=mkdir,proto3,oneof"`
}

type FsClient_Rename struct {
	Rename *FsRename `protobuf:"bytes,11,opt,name=rename,proto3,oneof"`
}

type FsClient_Remove struct {
	Remove *FsRemove `protobuf:"bytes,12,opt,name=remove,proto3,oneof"`
}

type FsClient_Cancel struct {
	Cancel *FsCancel `protobuf:"bytes,13,opt,name=cancel,proto3,oneof"`
}

type FsClient_Watch struct {
	Watch *FsWatch `protobuf:"bytes,14,opt,name=watch,proto3,oneof"`
}

type FsClient_Unwatch struct {
	Unwatch *FsUnwatch `protobuf:"bytes,15,opt,name=unwatch,proto3,oneof"`
}

func (*FsClient_Stat) isFsClient_Msg() {}

func (*FsClient_List) isFsClient_Msg() {}

func (*FsClient_Read) isFsClient_Msg() {}

func (*FsClient_Ack) isFsClient_Msg() {}

func (*FsClient_Write) isFsClient_Msg() {}

func (*FsClient_Data) isFsClient_Msg() {}

func (*FsClient_Commit) isFsClient_Msg() {}

func (*FsClient_Abort) isFsClient_Msg() {}

func (*FsClient_Mkdir) isFsClient_Msg() {}

func (*FsClient_Rename) isFsClient_Msg() {}

func (*FsClient_Remove) isFsClient_Msg() {}

func (*FsClient_Cancel) isFsClient_Msg() {}

func (*FsClient_Watch) isFsClient_Msg() {}

func (*FsClient_Unwatch) isFsClient_Msg() {}

type FsServer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	ReqId uint32                 `protobuf:"varint,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*FsServer_Entry
	//	*FsServer_Entries
	//	*FsServer_Chunk
	//	*FsServer_Eof
	//	*FsServer_Credit
	//	*FsServer_Ok
	//	*FsServer_Error
	//	*FsServer_Conflict
	//	*FsServer_Changed
	Msg           isFsServer_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsServer) Reset() {
	*x = FsServer{}
	mi := &file_tilder_v1_fs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsServer) ProtoMessage() {}

func (x *FsServer) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_fs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsServer.ProtoReflect.Descriptor instead.
func (*FsServer) Descriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{1}
}

func (x *FsServer) GetReqId() uint32 {
	if x != nil {
		return x.ReqId
	}
	return 0
}

func (x *FsServer) GetMsg() isFsServer_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *FsServer) GetEntry() *FsEntry {
	if x != nil {
		if x, ok := x.Msg.(*FsServer_Entry); ok {
			return x.Entry
		}
	}
	return nil
}

func (x *FsServer) GetEntries() *FsEntries {
	if x != nil {
		if x, ok := x.Msg.(*FsServer_Entries); ok {
			return x.Entries
		}
	}
	return nil
}

func (x *FsServer) GetChunk() *FsChunk {
	if x != nil {
		if x, ok := x.Msg.(*FsServer_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *FsServer) GetEof() *FsEof {
	if x != nil {
		if x, ok := x.Msg.(*FsServer_Eof); ok {
			return x.Eof
		}
	}
	return nil
}

func (x *FsServer) GetCredit() *FsCredit {
	if x != nil {
		if x, ok := x.Msg.(*FsServer_Credit); ok {
			return x.Credit
		}
	}
	return nil
}

func (x *FsServer) GetOk() *FsOk {
	if x != nil {
		if x, ok := x.Msg.(*FsServer_Ok); ok {
			return x.Ok
		}
	}
	return nil
}

func (x *FsServer) GetError() *FsError {
	if x != nil {
		if x, ok := x.Msg.(*FsServer_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *FsServer) GetConflict() *FsConflict {
	if x != nil {
		if x, ok := x.Msg.(*FsServer_Conflict); ok {
			return x.Conflict
		}
	}
	return nil
}

func (x *FsServer) GetChanged() *FsChanged {
	if x != nil {
		if x, ok := x.Msg.(*FsServer_Changed); ok {
			return x.Changed
		}
	}
	return nil
}

type isFsServer_Msg interface {
	isFsServer_Msg()
}

type FsServer_Entry struct {
	Entry *FsEntry `protobuf:"bytes,2,opt,name=entry,proto3,oneof"`
}

type FsServer_Entries struct {
	Entries *FsEntries `protobuf:"bytes,3,opt,name=entries,proto3,oneof"`
}

type FsServer_Chunk struct {
	Chunk *FsChunk `protobuf:"bytes,4,opt,name=chunk,proto3,oneof"`
}

type FsServer_Eof struct {
	Eof *FsEof `protobuf:"bytes,5,opt,name=eof,proto3,oneof"`
}

type FsServer_Credit struct {
	Credit *FsCredit `protobuf:"bytes,6,opt,name=credit,proto3,oneof"`
}

type FsServer_Ok struct {
	Ok *FsOk `protobuf:"bytes,7,opt,name=ok,proto3,oneof"`
}

type FsServer_Error struct {
	Error *FsError `protobuf:"bytes,8,opt,name=error,proto3,oneof"`
}

type FsServer_Conflict struct {
	Conflict *FsConflict `protobuf:"bytes,9,opt,name=conflict,proto3,oneof"`
}

type FsServer_Changed struct {
	Changed *FsChanged `protobuf:"bytes,10,opt,name=changed,proto3,oneof"`
}

func (*FsServer_Entry) isFsServer_Msg() {}

func (*FsServer_Entries) isFsServer_Msg() {}

func (*FsServer_Chunk) isFsServer_Msg() {}

func (*FsServer_Eof) isFsServer_Msg() {}

func (*FsServer_Credit) isFsServer_Msg() {}

func (*FsServer_Ok) isFsServer_Msg() {}

func (*FsServer_Error) isFsServer_Msg() {}

func (*FsServer_Conflict) isFsServer_Msg() {}

func (*FsServer_Changed) isFsServer_Msg() {}

type FsStat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []byte                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsStat) Reset() {
	*x = FsStat{}
	mi := &file_tilder_v1_fs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsStat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsStat) ProtoMessage() {}

func (x *FsStat) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_fs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsStat.ProtoReflect.Descriptor instead.
func (*FsStat) Descriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{2}
}

func (x *FsStat) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

// A page of a directory, sorted by name bytes, after the name `after`. A page
// is cut to fit one message; `next` continues it, empty at the end.
type FsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []byte                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	After         []byte                 `protobuf:"bytes,2,opt,name=after,proto3" json:"after,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsList) Reset() {
	*x = FsList{}
	mi := &file_tilder_v1_fs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsList) ProtoMessage() {}

func (x *FsList) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_fs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsList.ProtoReflect.Descriptor instead.
func (*FsList) Descriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{3}
}

func (x *FsList) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *FsList) GetAfter() []byte {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *FsList) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// Streams bytes [offset, offset+length) (length 0: to the end) as FsChunks,
// then FsEof. At most `window` bytes (the agent clamps it to
// [64 KiB, 1 MiB]) go unacknowledged.
type FsRead struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []byte                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Length        uint64                 `protobuf:"varint,3,opt,name=length,proto3" json:"length,omitempty"`
	Window        uint32                 `protobuf:"varint,4,opt,name=window,proto3" json:"window,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsRead) Reset() {
	*x = FsRead{}
	mi := &file_tilder_v1_fs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsRead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsRead) ProtoMessage() {}

func (x *FsRead) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_fs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsRead.ProtoReflect.Descriptor instead.
func (*FsRead) Descriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{4}
}

func (x *FsRead) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *FsRead) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FsRead) GetLength() uint64 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *FsRead) GetWindow() uint32 {
	if x != nil {
		return x.Window
	}
	return 0
}

// The bytes of a read received so far, counted from its start.
type FsAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      uint64                 `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsAck) Reset() {
	*x = FsAck{}
	mi := &file_tilder_v1_fs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsAck) ProtoMessage() {}

func (x *FsAck) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_fs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsAck.ProtoReflect.Descriptor instead.
func (*FsAck) Descriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{5}
}

func (x *FsAck) GetReceived() uint64 {
	if x != nil {
		return x.Received
	}
	return 0
}

// Starts a write; FsData follows as the agent grants FsCredit, then FsCommit
// (or FsAbort). With if_etag the commit fails with FsConflict if the file
// changed since it had that etag; with create_only, if it exists.
type FsWrite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []byte                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	IfEtag        []byte                 `protobuf:"bytes,2,opt,name=if_etag,json=ifEtag,proto3" json:"if_etag,omitempty"`
	CreateOnly    bool                   `protobuf:"varint,3,opt,name=create_only,json=createOnly,proto3" json:"create_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsWrite) Reset() {
	*x = FsWrite{}
	mi := &file_tilder_v1_fs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsWrite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsWrite) ProtoMessage() {}

func (x *FsWrite) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_fs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsWrite.ProtoReflect.Descriptor instead.
func (*FsWrite) Descriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{6}
}

func (x *FsWrite) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *FsWrite) GetIfEtag() []byte {
	if x != nil {
		return x.IfEtag
	}
	return nil
}

func (x *FsWrite) GetCreateOnly() bool {
	if x != nil {
		return x.CreateOnly
	}
	return false
}

type FsData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsData) Reset() {
	*x = FsData{}
	mi := &file_tilder_v1_fs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsData) ProtoMessage() {}

func (x *FsData) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_fs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsData.ProtoReflect.Descriptor instead.
func (*FsData) Descriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{7}
}

func (x *FsData) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type FsCommit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsCommit) Reset() {
	*x = FsCommit{}
	mi := &file_tilder_v1_fs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsCommit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsCommit) ProtoMessage() {}

func (x *FsCommit) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_fs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsCommit.ProtoReflect.Descriptor instead.
func (*FsCommit) Descriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{8}
}

type FsAbort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsAbort) Reset() {
	*x = FsAbort{}
	mi := &file_tilder_v1_fs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsAbort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsAbort) ProtoMessage() {}

func (x *FsAbort) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_fs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsAbort.ProtoReflect.Descriptor instead.
func (*FsAbort) Descriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{9}
}

type FsMkdir struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []byte                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsMkdir) Reset() {
	*x = FsMkdir{}
	mi := &file_tilder_v1_fs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsMkdir) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsMkdir) ProtoMessage() {}

func (x *FsMkdir) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_fs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsMkdir.ProtoReflect.Descriptor instead.
func (*FsMkdir) Descriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{10}
}

func (x *FsMkdir) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

type FsRename struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          []byte                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            []byte                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	NoReplace     bool                   `protobuf:"varint,3,opt,name=no_replace,json=noReplace,proto3" json:"no_replace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsRename) Reset() {
	*x = FsRename{}
	mi := &file_tilder_v1_fs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsRename) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsRename) ProtoMessage() {}

func (x *FsRename) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_fs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsRename.ProtoReflect.Descriptor instead.
func (*FsRename) Descriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{11}
}

func (x *FsRename) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *FsRename) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *FsRename) GetNoReplace() bool {
	if x != nil {
		return x.NoReplace
	}
	return false
}

type FsRemove struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []byte                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsRemove) Reset() {
	*x = FsRemove{}
	mi := &file_tilder_v1_fs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsRemove) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsRemove) ProtoMessage() {}

func (x *FsRemove) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_fs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsRemove.ProtoReflect.Descriptor instead.
func (*FsRemove) Descriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{12}
}

func (x *FsRemove) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *FsRemove) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

// Stops the request with this id: a read stops sending, a write is dropped.
type FsCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsCancel) Reset() {
	*x = FsCancel{}
	mi := &file_tilder_v1_fs_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsCancel) ProtoMessage() {}

func (x *FsCancel) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_fs_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsCancel.ProtoReflect.Descriptor instead.
func (*FsCancel) Descriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{13}
}

// Watches one directory (not what is under it) while it is open in the UI;
// FsChanged messages carry this request's id until FsUnwatch with the same id.
type FsWatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          []byte                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsWatch) Reset() {
	*x = FsWatch{}
	mi := &file_tilder_v1_fs_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsWatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsWatch) ProtoMessage() {}

func (x *FsWatch) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_fs_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsWatch.ProtoReflect.Descriptor instead.
func (*FsWatch) Descriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{14}
}

func (x *FsWatch) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

type FsUnwatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsUnwatch) Reset() {
	*x = FsUnwatch{}
	mi := &file_tilder_v1_fs_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsUnwatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsUnwatch) ProtoMessage() {}

func (x *FsUnwatch) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_fs_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsUnwatch.ProtoReflect.Descriptor instead.
func (*FsUnwatch) Descriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{15}
}

// Names in a watched directory that changed (created, written or removed:
// the console looks again). `rescan` means too many to list, or events were
// lost: read the whole directory again.
type FsChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Names         [][]byte               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	Rescan        bool                   `protobuf:"varint,2,opt,name=rescan,proto3" json:"rescan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsChanged) Reset() {
	*x = FsChanged{}
	mi := &file_tilder_v1_fs_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsChanged) ProtoMessage() {}

func (x *FsChanged) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_fs_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsChanged.ProtoReflect.Descriptor instead.
func (*FsChanged) Descriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{16}
}

func (x *FsChanged) GetNames() [][]byte {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *FsChanged) GetRescan() bool {
	if x != nil {
		return x.Rescan
	}
	return false
}

type FsEntry struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Name    []byte                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Kind    FsKind                 `protobuf:"varint,2,opt,name=kind,proto3,enum=tilder.v1.FsKind" json:"kind,omitempty"`
	Size    uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	MtimeNs int64                  `protobuf:"varint,4,opt,name=mtime_ns,json=mtimeNs,proto3" json:"mtime_ns,omitempty"`
	Perm    uint32                 `protobuf:"varint,5,opt,name=perm,proto3" json:"perm,omitempty"`
	// Changes whenever the file does: what a write's if_etag names.
	Etag       []byte `protobuf:"bytes,6,opt,name=etag,proto3" json:"etag,omitempty"`
	LinkTarget []byte `protobuf:"bytes,7,opt,name=link_target,json=linkTarget,proto3" json:"link_target,omitempty"`
	LinkKind   FsKind `protobuf:"varint,8,opt,name=link_kind,json=linkKind,proto3,enum=tilder.v1.FsKind" json:"link_kind,omitempty"`
	// A link that points nowhere, or above its directory (never followed).
	Dangling      bool `protobuf:"varint,9,opt,name=dangling,proto3" json:"dangling,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsEntry) Reset() {
	*x = FsEntry{}
	mi := &file_tilder_v1_fs_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsEntry) ProtoMessage() {}

func (x *FsEntry) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_fs_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsEntry.ProtoReflect.Descriptor instead.
func (*FsEntry) Descriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{17}
}

func (x *FsEntry) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *FsEntry) GetKind() FsKind {
	if x != nil {
		return x.Kind
	}
	return FsKind_FS_KIND_UNSPECIFIED
}

func (x *FsEntry) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FsEntry) GetMtimeNs() int64 {
	if x != nil {
		return x.MtimeNs
	}
	return 0
}

func (x *FsEntry) GetPerm() uint32 {
	if x != nil {
		return x.Perm
	}
	return 0
}

func (x *FsEntry) GetEtag() []byte {
	if x != nil {
		return x.Etag
	}
	return nil
}

func (x *FsEntry) GetLinkTarget() []byte {
	if x != nil {
		return x.LinkTarget
	}
	return nil
}

func (x *FsEntry) GetLinkKind() FsKind {
	if x != nil {
		return x.LinkKind
	}
	return FsKind_FS_KIND_UNSPECIFIED
}

func (x *FsEntry) GetDangling() bool {
	if x != nil {
		return x.Dangling
	}
	return false
}

type FsEntries struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Entries []*FsEntry             `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Next    []byte                 `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	// The directory holds more names than the agent lists.
	Truncated     bool `protobuf:"varint,3,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsEntries) Reset() {
	*x = FsEntries{}
	mi := &file_tilder_v1_fs_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsEntries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsEntries) ProtoMessage() {}

func (x *FsEntries) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_fs_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsEntries.ProtoReflect.Descriptor instead.
func (*FsEntries) Descriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{18}
}

func (x *FsEntries) GetEntries() []*FsEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *FsEntries) GetNext() []byte {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *FsEntries) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type FsChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        uint64                 `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsChunk) Reset() {
	*x = FsChunk{}
	mi := &file_tilder_v1_fs_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsChunk) ProtoMessage() {}

func (x *FsChunk) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_fs_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsChunk.ProtoReflect.Descriptor instead.
func (*FsChunk) Descriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{19}
}

func (x *FsChunk) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *FsChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// The end of a read: the file as read, and the SHA-256 of the bytes sent.
type FsEof struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *FsEntry               `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Sha256        []byte                 `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsEof) Reset() {
	*x = FsEof{}
	mi := &file_tilder_v1_fs_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsEof) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsEof) ProtoMessage() {}

func (x *FsEof) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_fs_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsEof.ProtoReflect.Descriptor instead.
func (*FsEof) Descriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{20}
}

func (x *FsEof) GetEntry() *FsEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *FsEof) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

// Total bytes of this write the client may have sent so far: it paces
// itself by this, so a big upload does not hold up the shells.
type FsCredit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      uint64                 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsCredit) Reset() {
	*x = FsCredit{}
	mi := &file_tilder_v1_fs_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsCredit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsCredit) ProtoMessage() {}

func (x *FsCredit) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_fs_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsCredit.ProtoReflect.Descriptor instead.
func (*FsCredit) Descriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{21}
}

func (x *FsCredit) GetAccepted() uint64 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

type FsOk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *FsEntry               `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsOk) Reset() {
	*x = FsOk{}
	mi := &file_tilder_v1_fs_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsOk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsOk) ProtoMessage() {}

func (x *FsOk) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_fs_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsOk.ProtoReflect.Descriptor instead.
func (*FsOk) Descriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{22}
}

func (x *FsOk) GetEntry() *FsEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

type FsError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          FsError_Code           `protobuf:"varint,1,opt,name=code,proto3,enum=tilder.v1.FsError_Code" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsError) Reset() {
	*x = FsError{}
	mi := &file_tilder_v1_fs_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsError) ProtoMessage() {}

func (x *FsError) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_fs_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsError.ProtoReflect.Descriptor instead.
func (*FsError) Descriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{23}
}

func (x *FsError) GetCode() FsError_Code {
	if x != nil {
		return x.Code
	}
	return FsError_CODE_UNSPECIFIED
}

type FsConflict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Current       *FsEntry               `protobuf:"bytes,1,opt,name=current,proto3" json:"current,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsConflict) Reset() {
	*x = FsConflict{}
	mi := &file_tilder_v1_fs_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsConflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsConflict) ProtoMessage() {}

func (x *FsConflict) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_fs_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsConflict.ProtoReflect.Descriptor instead.
func (*FsConflict) Descriptor() ([]byte, []int) {
	return file_tilder_v1_fs_proto_rawDescGZIP(), []int{24}
}

func (x *FsConflict) GetCurrent() *FsEntry {
	if x != nil {
		return x.Current
	}
	return nil
}

var File_tilder_v1_fs_proto protoreflect.FileDescriptor

const file_tilder_v1_fs_proto_rawDesc = "" +
	"\n" +
	"\x12tilder/v1/fs.proto\x12\ttilder.v1\"\x90\x05\n" +
	"\bFsClient\x12\x15\n" +
	"\x06req_id\x18\x01 \x01(\rR\x05reqId\x12'\n" +
	"\x04stat\x18\x02 \x01(\v2\x11.tilder.v1.FsStatH\x00R\x04stat\x12'\n" +
	"\x04list\x18\x03 \x01(\v2\x11.tilder.v1.FsListH\x00R\x04list\x12'\n" +
	"\x04read\x18\x04 \x01(\v2\x11.tilder.v1.FsReadH\x00R\x04read\x12$\n" +
	"\x03ack\x18\x05 \x01(\v2\x10.tilder.v1.FsAckH\x00R\x03ack\x12*\n" +
	"\x05write\x18\x06 \x01(\v2\x12.tilder.v1.FsWriteH\x00R\x05write\x12'\n" +
	"\x04data\x18\a \x01(\v2\x11.tilder.v1.FsDataH\x00R\x04data\x12-\n" +
	"\x06commit\x18\b \x01(\v2\x13.tilder.v1.FsCommitH\x00R\x06commit\x12*\n" +
	"\x05abort\x18\t \x01(\v2\x12.tilder.v1.FsAbortH\x00R\x05abort\x12*\n" +
	"\x05mkdir\x18\n" +
	" \x01(\v2\x12.tilder.v1.FsMkdirH\x00R\x05mkdir\x12-\n" +
	"\x06rename\x18\v \x01(\v2\x13.tilder.v1.FsRenameH\x00R\x06rename\x12-\n" +
	"\x06remove\x18\f \x01(\v2\x13.tilder.v1.FsRemoveH\x00R\x06remove\x12-\n" +
	"\x06cancel\x18\r \x01(\v2\x13.tilder.v1.FsCancelH\x00R\x06cancel\x12*\n" +
	"\x05watch\x18\x0e \x01(\v2\x12.tilder.v1.FsWatchH\x00R\x05watch\x120\n" +
	"\aunwatch\x18\x0f \x01(\v2\x14.tilder.v1.FsUnwatchH\x00R\aunwatchB\x05\n" +
	"\x03msg\"\xbd\x03\n" +
	"\bFsServer\x12\x15\n" +
	"\x06req_id\x18\x01 \x01(\rR\x05reqId\x12*\n" +
	"\x05entry\x18\x02 \x01(\v2\x12.tilder.v1.FsEntryH\x00R\x05entry\x120\n" +
	"\aentries\x18\x03 \x01(\v2\x14.tilder.v1.FsEntriesH\x00R\aentries\x12*\n" +
	"\x05chunk\x18\x04 \x01(\v2\x12.tilder.v1.FsChunkH\x00R\x05chunk\x12$\n" +
	"\x03eof\x18\x05 \x01(\v2\x10.tilder.v1.FsEofH\x00R\x03eof\x12-\n" +
	"\x06credit\x18\x06 \x01(\v2\x13.tilder.v1.FsCreditH\x00R\x06credit\x12!\n" +
	"\x02ok\x18\a \x01(\v2\x0f.tilder.v1.FsOkH\x00R\x02ok\x12*\n" +
	"\x05error\x18\b \x01(\v2\x12.tilder.v1.FsErrorH\x00R\x05error\x123\n" +
	"\bconflict\x18\t \x01(\v2\x15.tilder.v1.FsConflictH\x00R\bconflict\x120\n" +
	"\achanged\x18\n" +
	" \x01(\v2\x14.tilder.v1.FsChangedH\x00R\achangedB\x05\n" +
	"\x03msg\"\x1c\n" +
	"\x06FsStat\x12\x12\n" +
	"\x04path\x18\x01 \x01(\fR\x04path\"H\n" +
	"\x06FsList\x12\x12\n" +
	"\x04path\x18\x01 \x01(\fR\x04path\x12\x14\n" +
	"\x05after\x18\x02 \x01(\fR\x05after\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\"d\n" +
	"\x06FsRead\x12\x12\n" +
	"\x04path\x18\x01 \x01(\fR\x04path\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x04R\x06length\x12\x16\n" +
	"\x06window\x18\x04 \x01(\rR\x06window\"#\n" +
	"\x05FsAck\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\x04R\breceived\"W\n" +
	"\aFsWrite\x12\x12\n" +
	"\x04path\x18\x01 \x01(\fR\x04path\x12\x17\n" +
	"\aif_etag\x18\x02 \x01(\fR\x06ifEtag\x12\x1f\n" +
	"\vcreate_only\x18\x03 \x01(\bR\n" +
	"createOnly\"\x1c\n" +
	"\x06FsData\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\n" +
	"\n" +
	"\bFsCommit\"\t\n" +
	"\aFsAbort\"\x1d\n" +
	"\aFsMkdir\x12\x12\n" +
	"\x04path\x18\x01 \x01(\fR\x04path\"M\n" +
	"\bFsRename\x12\x12\n" +
	"\x04from\x18\x01 \x01(\fR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\fR\x02to\x12\x1d\n" +
	"\n" +
	"no_replace\x18\x03 \x01(\bR\tnoReplace\"<\n" +
	"\bFsRemove\x12\x12\n" +
	"\x04path\x18\x01 \x01(\fR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\"\n" +
	"\n" +
	"\bFsCancel\"\x1d\n" +
	"\aFsWatch\x12\x12\n" +
	"\x04path\x18\x01 \x01(\fR\x04path\"\v\n" +
	"\tFsUnwatch\"9\n" +
	"\tFsChanged\x12\x14\n" +
	"\x05names\x18\x01 \x03(\fR\x05names\x12\x16\n" +
	"\x06rescan\x18\x02 \x01(\bR\x06rescan\"\x88\x02\n" +
	"\aFsEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\fR\x04name\x12%\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x11.tilder.v1.FsKindR\x04kind\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x19\n" +
	"\bmtime_ns\x18\x04 \x01(\x03R\amtimeNs\x12\x12\n" +
	"\x04perm\x18\x05 \x01(\rR\x04perm\x12\x12\n" +
	"\x04etag\x18\x06 \x01(\fR\x04etag\x12\x1f\n" +
	"\vlink_target\x18\a \x01(\fR\n" +
	"linkTarget\x12.\n" +
	"\tlink_kind\x18\b \x01(\x0e2\x11.tilder.v1.FsKindR\blinkKind\x12\x1a\n" +
	"\bdangling\x18\t \x01(\bR\bdangling\"k\n" +
	"\tFsEntries\x12,\n" +
	"\aentries\x18\x01 \x03(\v2\x12.tilder.v1.FsEntryR\aentries\x12\x12\n" +
	"\x04next\x18\x02 \x01(\fR\x04next\x12\x1c\n" +
	"\ttruncated\x18\x03 \x01(\bR\ttruncated\"5\n" +
	"\aFsChunk\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x04R\x06offset\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"I\n" +
	"\x05FsEof\x12(\n" +
	"\x05entry\x18\x01 \x01(\v2\x12.tilder.v1.FsEntryR\x05entry\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\fR\x06sha256\"&\n" +
	"\bFsCredit\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x04R\baccepted\"0\n" +
	"\x04FsOk\x12(\n" +
	"\x05entry\x18\x01 \x01(\v2\x12.tilder.v1.FsEntryR\x05entry\"\xa1\x02\n" +
	"\aFsError\x12+\n" +
	"\x04code\x18\x01 \x01(\x0e2\x17.tilder.v1.FsError.CodeR\x04code\"\xe8\x01\n" +
	"\x04Code\x12\x14\n" +
	"\x10CODE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vCODE_DENIED\x10\x01\x12\x12\n" +
	"\x0eCODE_NOT_FOUND\x10\x02\x12\x0f\n" +
	"\vCODE_EXISTS\x10\x03\x12\x10\n" +
	"\fCODE_NOT_DIR\x10\x04\x12\x0f\n" +
	"\vCODE_IS_DIR\x10\x05\x12\x14\n" +
	"\x10CODE_NOT_REGULAR\x10\x06\x12\x11\n" +
	"\rCODE_CONFLICT\x10\a\x12\x10\n" +
	"\fCODE_INVALID\x10\b\x12\x11\n" +
	"\rCODE_NO_SPACE\x10\t\x12\r\n" +
	"\tCODE_BUSY\x10\n" +
	"\x12\x14\n" +
	"\x10CODE_WATCH_LIMIT\x10\v\":\n" +
	"\n" +
	"FsConflict\x12,\n" +
	"\acurrent\x18\x01 \x01(\v2\x12.tilder.v1.FsEntryR\acurrent*l\n" +
	"\x06FsKind\x12\x17\n" +
	"\x13FS_KIND_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fFS_KIND_FILE\x10\x01\x12\x0f\n" +
	"\vFS_KIND_DIR\x10\x02\x12\x13\n" +
	"\x0fFS_KIND_SYMLINK\x10\x03\x12\x11\n" +
	"\rFS_KIND_OTHER\x10\x04B?Z=github.com/nghyane/tilder/go/internal/wire/tilder/v1;tilderv1b\x06proto3"

var (
	file_tilder_v1_fs_proto_rawDescOnce sync.Once
	file_tilder_v1_fs_proto_rawDescData []byte
)

func file_tilder_v1_fs_proto_rawDescGZIP() []byte {
	file_tilder_v1_fs_proto_rawDescOnce.Do(func() {
		file_tilder_v1_fs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tilder_v1_fs_proto_rawDesc), len(file_tilder_v1_fs_proto_rawDesc)))
	})
	return file_tilder_v1_fs_proto_rawDescData
}

var file_tilder_v1_fs_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tilder_v1_fs_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_tilder_v1_fs_proto_goTypes = []any{
	(FsKind)(0),        // 0: tilder.v1.FsKind
	(FsError_Code)(0),  // 1: tilder.v1.FsError.Code
	(*FsClient)(nil),   // 2: tilder.v1.FsClient
	(*FsServer)(nil),   // 3: tilder.v1.FsServer
	(*FsStat)(nil),     // 4: tilder.v1.FsStat
	(*FsList)(nil),     // 5: tilder.v1.FsList
	(*FsRead)(nil),     // 6: tilder.v1.FsRead
	(*FsAck)(nil),      // 7: tilder.v1.FsAck
	(*FsWrite)(nil),    // 8: tilder.v1.FsWrite
	(*FsData)(nil),     // 9: tilder.v1.FsData
	(*FsCommit)(nil),   // 10: tilder.v1.FsCommit
	(*FsAbort)(nil),    // 11: tilder.v1.FsAbort
	(*FsMkdir)(nil),    // 12: tilder.v1.FsMkdir
	(*FsRename)(nil),   // 13: tilder.v1.FsRename
	(*FsRemove)(nil),   // 14: tilder.v1.FsRemove
	(*FsCancel)(nil),   // 15: tilder.v1.FsCancel
	(*FsWatch)(nil),    // 16: tilder.v1.FsWatch
	(*FsUnwatch)(nil),  // 17: tilder.v1.FsUnwatch
	(*FsChanged)(nil),  // 18: tilder.v1.FsChanged
	(*FsEntry)(nil),    // 19: tilder.v1.FsEntry
	(*FsEntries)(nil),  // 20: tilder.v1.FsEntries
	(*FsChunk)(nil),    // 21: tilder.v1.FsChunk
	(*FsEof)(nil),      // 22: tilder.v1.FsEof
	(*FsCredit)(nil),   // 23: tilder.v1.FsCredit
	(*FsOk)(nil),       // 24: tilder.v1.FsOk
	(*FsError)(nil),    // 25: tilder.v1.FsError
	(*FsConflict)(nil), // 26: tilder.v1.FsConflict
}
var file_tilder_v1_fs_proto_depIdxs = []int32{
	4,  // 0: tilder.v1.FsClient.stat:type_name -> tilder.v1.FsStat
	5,  // 1: tilder.v1.FsClient.list:type_name -> tilder.v1.FsList
	6,  // 2: tilder.v1.FsClient.read:type_name -> tilder.v1.FsRead
	7,  // 3: tilder.v1.FsClient.ack:type_name -> tilder.v1.FsAck
	8,  // 4: tilder.v1.FsClient.write:type_name -> tilder.v1.FsWrite
	9,  // 5: tilder.v1.FsClient.data:type_name -> tilder.v1.FsData
	10, // 6: tilder.v1.FsClient.commit:type_name -> tilder.v1.FsCommit
	11, // 7: tilder.v1.FsClient.abort:type_name -> tilder.v1.FsAbort
	12, // 8: tilder.v1.FsClient.mkdir:type_name -> tilder.v1.FsMkdir
	13, // 9: tilder.v1.FsClient.rename:type_name -> tilder.v1.FsRename
	14, // 10: tilder.v1.FsClient.remove:type_name -> tilder.v1.FsRemove
	15, // 11: tilder.v1.FsClient.cancel:type_name -> tilder.v1.FsCancel
	16, // 12: tilder.v1.FsClient.watch:type_name -> tilder.v1.FsWatch
	17, // 13: tilder.v1.FsClient.unwatch:type_name -> tilder.v1.FsUnwatch
	19, // 14: tilder.v1.FsServer.entry:type_name -> tilder.v1.FsEntry
	20, // 15: tilder.v1.FsServer.entries:type_name -> tilder.v1.FsEntries
	21, // 16: tilder.v1.FsServer.chunk:type_name -> tilder.v1.FsChunk
	22, // 17: tilder.v1.FsServer.eof:type_name -> tilder.v1.FsEof
	23, // 18: tilder.v1.FsServer.credit:type_name -> tilder.v1.FsCredit
	24, // 19: tilder.v1.FsServer.ok:type_name -> tilder.v1.FsOk
	25, // 20: tilder.v1.FsServer.error:type_name -> tilder.v1.FsError
	26, // 21: tilder.v1.FsServer.conflict:type_name -> tilder.v1.FsConflict
	18, // 22: tilder.v1.FsServer.changed:type_name -> tilder.v1.FsChanged
	0,  // 23: tilder.v1.FsEntry.kind:type_name -> tilder.v1.FsKind
	0,  // 24: tilder.v1.FsEntry.link_kind:type_name -> tilder.v1.FsKind
	19, // 25: tilder.v1.FsEntries.entries:type_name -> tilder.v1.FsEntry
	19, // 26: tilder.v1.FsEof.entry:type_name -> tilder.v1.FsEntry
	19, // 27: tilder.v1.FsOk.entry:type_name -> tilder.v1.FsEntry
	1,  // 28: tilder.v1.FsError.code:type_name -> tilder.v1.FsError.Code
	19, // 29: tilder.v1.FsConflict.current:type_name -> tilder.v1.FsEntry
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_tilder_v1_fs_proto_init() }
func file_tilder_v1_fs_proto_init() {
	if File_tilder_v1_fs_proto != nil {
		return
	}
	file_tilder_v1_fs_proto_msgTypes[0].OneofWrappers = []any{
		(*FsClient_Stat)(nil),
		(*FsClient_List)(nil),
		(*FsClient_Read)(nil),
		(*FsClient_Ack)(nil),
		(*FsClient_Write)(nil),
		(*FsClient_Data)(nil),
		(*FsClient_Commit)(nil),
		(*FsClient_Abort)(nil),
		(*FsClient_Mkdir)(nil),
		(*FsClient_Rename)(nil),
		(*FsClient_Remove)(nil),
		(*FsClient_Cancel)(nil),
		(*FsClient_Watch)(nil),
		(*FsClient_Unwatch)(nil),
	}
	file_tilder_v1_fs_proto_msgTypes[1].OneofWrappers = []any{
		(*FsServer_Entry)(nil),
		(*FsServer_Entries)(nil),
		(*FsServer_Chunk)(nil),
		(*FsServer_Eof)(nil),
		(*FsServer_Credit)(nil),
		(*FsServer_Ok)(nil),
		(*FsServer_Error)(nil),
		(*FsServer_Conflict)(nil),
		(*FsServer_Changed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tilder_v1_fs_proto_rawDesc), len(file_tilder_v1_fs_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tilder_v1_fs_proto_goTypes,
		DependencyIndexes: file_tilder_v1_fs_proto_depIdxs,
		EnumInfos:         file_tilder_v1_fs_proto_enumTypes,
		MessageInfos:      file_tilder_v1_fs_proto_msgTypes,
	}.Build()
	File_tilder_v1_fs_proto = out.File
	file_tilder_v1_fs_proto_goTypes = nil
	file_tilder_v1_fs_proto_depIdxs = nil
}
