// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: tilder/v1/hello.proto

// The first message on every connection (PROTOCOL §1): both sides use the
// lower protocol number, and new behaviour travels as named features rather
// than version bumps.

package tilderv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      uint32                 `protobuf:"varint,1,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Features      []string               `protobuf:"bytes,2,rep,name=features,proto3" json:"features,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_tilder_v1_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_tilder_v1_hello_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetProtocol() uint32 {
	if x != nil {
		return x.Protocol
	}
	return 0
}

func (x *Hello) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

var File_tilder_v1_hello_proto protoreflect.FileDescriptor

const file_tilder_v1_hello_proto_rawDesc = "" +
	"\n" +
	"\x15tilder/v1/hello.proto\x12\ttilder.v1\"?\n" +
	"\x05Hello\x12\x1a\n" +
	"\bprotocol\x18\x01 \x01(\rR\bprotocol\x12\x1a\n" +
	"\bfeatures\x18\x02 \x03(\tR\bfeaturesB?Z=github.com/nghyane/tilder/go/internal/wire/tilder/v1;tilderv1b\x06proto3"

var (
	file_tilder_v1_hello_proto_rawDescOnce sync.Once
	file_tilder_v1_hello_proto_rawDescData []byte
)

func file_tilder_v1_hello_proto_rawDescGZIP() []byte {
	file_tilder_v1_hello_proto_rawDescOnce.Do(func() {
		file_tilder_v1_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tilder_v1_hello_proto_rawDesc), len(file_tilder_v1_hello_proto_rawDesc)))
	})
	return file_tilder_v1_hello_proto_rawDescData
}

var file_tilder_v1_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tilder_v1_hello_proto_goTypes = []any{
	(*Hello)(nil), // 0: tilder.v1.Hello
}
var file_tilder_v1_hello_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tilder_v1_hello_proto_init() }
func file_tilder_v1_hello_proto_init() {
	if File_tilder_v1_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tilder_v1_hello_proto_rawDesc), len(file_tilder_v1_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tilder_v1_hello_proto_goTypes,
		DependencyIndexes: file_tilder_v1_hello_proto_depIdxs,
		MessageInfos:      file_tilder_v1_hello_proto_msgTypes,
	}.Build()
	File_tilder_v1_hello_proto = out.File
	file_tilder_v1_hello_proto_goTypes = nil
	file_tilder_v1_hello_proto_depIdxs = nil
}
