// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: tilder/v1/holder.proto

// Between the agent and a holder process, over a unix socket in the owner's
// run directory (ADR 0005). Local only, and meant almost never to change: a
// holder keeps running the code it was started with, so a newer agent must
// speak every contract_version still alive.

package tilderv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Agent → holder. A connection starts with Hello; then it may Attach (and
// receive the replay and the stream) and send input, resizes and a kill.
type HolderRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*HolderRequest_Hello
	//	*HolderRequest_Attach
	//	*HolderRequest_Input
	//	*HolderRequest_Resize
	//	*HolderRequest_Kill
	Msg           isHolderRequest_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HolderRequest) Reset() {
	*x = HolderRequest{}
	mi := &file_tilder_v1_holder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderRequest) ProtoMessage() {}

func (x *HolderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_holder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolderRequest.ProtoReflect.Descriptor instead.
func (*HolderRequest) Descriptor() ([]byte, []int) {
	return file_tilder_v1_holder_proto_rawDescGZIP(), []int{0}
}

func (x *HolderRequest) GetMsg() isHolderRequest_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *HolderRequest) GetHello() *HolderHello {
	if x != nil {
		if x, ok := x.Msg.(*HolderRequest_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *HolderRequest) GetAttach() *HolderAttach {
	if x != nil {
		if x, ok := x.Msg.(*HolderRequest_Attach); ok {
			return x.Attach
		}
	}
	return nil
}

func (x *HolderRequest) GetInput() *PtyInput {
	if x != nil {
		if x, ok := x.Msg.(*HolderRequest_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *HolderRequest) GetResize() *Resize {
	if x != nil {
		if x, ok := x.Msg.(*HolderRequest_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *HolderRequest) GetKill() *Kill {
	if x != nil {
		if x, ok := x.Msg.(*HolderRequest_Kill); ok {
			return x.Kill
		}
	}
	return nil
}

type isHolderRequest_Msg interface {
	isHolderRequest_Msg()
}

type HolderRequest_Hello struct {
	Hello *HolderHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type HolderRequest_Attach struct {
	Attach *HolderAttach `protobuf:"bytes,2,opt,name=attach,proto3,oneof"`
}

type HolderRequest_Input struct {
	Input *PtyInput `protobuf:"bytes,3,opt,name=input,proto3,oneof"`
}

type HolderRequest_Resize struct {
	Resize *Resize `protobuf:"bytes,4,opt,name=resize,proto3,oneof"`
}

type HolderRequest_Kill struct {
	Kill *Kill `protobuf:"bytes,5,opt,name=kill,proto3,oneof"`
}

func (*HolderRequest_Hello) isHolderRequest_Msg() {}

func (*HolderRequest_Attach) isHolderRequest_Msg() {}

func (*HolderRequest_Input) isHolderRequest_Msg() {}

func (*HolderRequest_Resize) isHolderRequest_Msg() {}

func (*HolderRequest_Kill) isHolderRequest_Msg() {}

type HolderHello struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractVersion uint32                 `protobuf:"varint,1,opt,name=contract_version,json=contractVersion,proto3" json:"contract_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HolderHello) Reset() {
	*x = HolderHello{}
	mi := &file_tilder_v1_holder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderHello) ProtoMessage() {}

func (x *HolderHello) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_holder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolderHello.ProtoReflect.Descriptor instead.
func (*HolderHello) Descriptor() ([]byte, []int) {
	return file_tilder_v1_holder_proto_rawDescGZIP(), []int{1}
}

func (x *HolderHello) GetContractVersion() uint32 {
	if x != nil {
		return x.ContractVersion
	}
	return 0
}

type HolderAttach struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Since         uint64                 `protobuf:"varint,1,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HolderAttach) Reset() {
	*x = HolderAttach{}
	mi := &file_tilder_v1_holder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderAttach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderAttach) ProtoMessage() {}

func (x *HolderAttach) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_holder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolderAttach.ProtoReflect.Descriptor instead.
func (*HolderAttach) Descriptor() ([]byte, []int) {
	return file_tilder_v1_holder_proto_rawDescGZIP(), []int{2}
}

func (x *HolderAttach) GetSince() uint64 {
	if x != nil {
		return x.Since
	}
	return 0
}

// Holder → agent.
type HolderEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*HolderEvent_Welcome
	//	*HolderEvent_Replay
	//	*HolderEvent_Output
	//	*HolderEvent_Exit
	Msg           isHolderEvent_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HolderEvent) Reset() {
	*x = HolderEvent{}
	mi := &file_tilder_v1_holder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderEvent) ProtoMessage() {}

func (x *HolderEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_holder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolderEvent.ProtoReflect.Descriptor instead.
func (*HolderEvent) Descriptor() ([]byte, []int) {
	return file_tilder_v1_holder_proto_rawDescGZIP(), []int{3}
}

func (x *HolderEvent) GetMsg() isHolderEvent_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *HolderEvent) GetWelcome() *HolderWelcome {
	if x != nil {
		if x, ok := x.Msg.(*HolderEvent_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *HolderEvent) GetReplay() *HolderReplay {
	if x != nil {
		if x, ok := x.Msg.(*HolderEvent_Replay); ok {
			return x.Replay
		}
	}
	return nil
}

func (x *HolderEvent) GetOutput() *Output {
	if x != nil {
		if x, ok := x.Msg.(*HolderEvent_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *HolderEvent) GetExit() *Exit {
	if x != nil {
		if x, ok := x.Msg.(*HolderEvent_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

type isHolderEvent_Msg interface {
	isHolderEvent_Msg()
}

type HolderEvent_Welcome struct {
	Welcome *HolderWelcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type HolderEvent_Replay struct {
	Replay *HolderReplay `protobuf:"bytes,2,opt,name=replay,proto3,oneof"`
}

type HolderEvent_Output struct {
	Output *Output `protobuf:"bytes,3,opt,name=output,proto3,oneof"`
}

type HolderEvent_Exit struct {
	Exit *Exit `protobuf:"bytes,4,opt,name=exit,proto3,oneof"`
}

func (*HolderEvent_Welcome) isHolderEvent_Msg() {}

func (*HolderEvent_Replay) isHolderEvent_Msg() {}

func (*HolderEvent_Output) isHolderEvent_Msg() {}

func (*HolderEvent_Exit) isHolderEvent_Msg() {}

type HolderWelcome struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ContractVersion uint32                 `protobuf:"varint,1,opt,name=contract_version,json=contractVersion,proto3" json:"contract_version,omitempty"`
	ShellId         string                 `protobuf:"bytes,2,opt,name=shell_id,json=shellId,proto3" json:"shell_id,omitempty"`
	Pid             int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HolderWelcome) Reset() {
	*x = HolderWelcome{}
	mi := &file_tilder_v1_holder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderWelcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderWelcome) ProtoMessage() {}

func (x *HolderWelcome) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_holder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolderWelcome.ProtoReflect.Descriptor instead.
func (*HolderWelcome) Descriptor() ([]byte, []int) {
	return file_tilder_v1_holder_proto_rawDescGZIP(), []int{4}
}

func (x *HolderWelcome) GetContractVersion() uint32 {
	if x != nil {
		return x.ContractVersion
	}
	return 0
}

func (x *HolderWelcome) GetShellId() string {
	if x != nil {
		return x.ShellId
	}
	return ""
}

func (x *HolderWelcome) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// What the attach missed: data from offset `from`, `lost` bytes no longer kept.
// From contract 2: `screen`, the screen as of the end of `data`, cols×rows
// (ADR 0017); a contract 1 holder leaves them empty.
type HolderReplay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	From          uint64                 `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	Lost          uint64                 `protobuf:"varint,3,opt,name=lost,proto3" json:"lost,omitempty"`
	Exited        bool                   `protobuf:"varint,4,opt,name=exited,proto3" json:"exited,omitempty"`
	Code          int32                  `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`
	Screen        []byte                 `protobuf:"bytes,6,opt,name=screen,proto3" json:"screen,omitempty"`
	Cols          uint32                 `protobuf:"varint,7,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,8,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HolderReplay) Reset() {
	*x = HolderReplay{}
	mi := &file_tilder_v1_holder_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HolderReplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HolderReplay) ProtoMessage() {}

func (x *HolderReplay) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_holder_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HolderReplay.ProtoReflect.Descriptor instead.
func (*HolderReplay) Descriptor() ([]byte, []int) {
	return file_tilder_v1_holder_proto_rawDescGZIP(), []int{5}
}

func (x *HolderReplay) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *HolderReplay) GetFrom() uint64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *HolderReplay) GetLost() uint64 {
	if x != nil {
		return x.Lost
	}
	return 0
}

func (x *HolderReplay) GetExited() bool {
	if x != nil {
		return x.Exited
	}
	return false
}

func (x *HolderReplay) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *HolderReplay) GetScreen() []byte {
	if x != nil {
		return x.Screen
	}
	return nil
}

func (x *HolderReplay) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *HolderReplay) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

var File_tilder_v1_holder_proto protoreflect.FileDescriptor

const file_tilder_v1_holder_proto_rawDesc = "" +
	"\n" +
	"\x16tilder/v1/holder.proto\x12\ttilder.v1\x1a\x13tilder/v1/pty.proto\"\xfa\x01\n" +
	"\rHolderRequest\x12.\n" +
	"\x05hello\x18\x01 \x01(\v2\x16.tilder.v1.HolderHelloH\x00R\x05hello\x121\n" +
	"\x06attach\x18\x02 \x01(\v2\x17.tilder.v1.HolderAttachH\x00R\x06attach\x12+\n" +
	"\x05input\x18\x03 \x01(\v2\x13.tilder.v1.PtyInputH\x00R\x05input\x12+\n" +
	"\x06resize\x18\x04 \x01(\v2\x11.tilder.v1.ResizeH\x00R\x06resize\x12%\n" +
	"\x04kill\x18\x05 \x01(\v2\x0f.tilder.v1.KillH\x00R\x04killB\x05\n" +
	"\x03msg\"8\n" +
	"\vHolderHello\x12)\n" +
	"\x10contract_version\x18\x01 \x01(\rR\x0fcontractVersion\"$\n" +
	"\fHolderAttach\x12\x14\n" +
	"\x05since\x18\x01 \x01(\x04R\x05since\"\xd1\x01\n" +
	"\vHolderEvent\x124\n" +
	"\awelcome\x18\x01 \x01(\v2\x18.tilder.v1.HolderWelcomeH\x00R\awelcome\x121\n" +
	"\x06replay\x18\x02 \x01(\v2\x17.tilder.v1.HolderReplayH\x00R\x06replay\x12+\n" +
	"\x06output\x18\x03 \x01(\v2\x11.tilder.v1.OutputH\x00R\x06output\x12%\n" +
	"\x04exit\x18\x04 \x01(\v2\x0f.tilder.v1.ExitH\x00R\x04exitB\x05\n" +
	"\x03msg\"g\n" +
	"\rHolderWelcome\x12)\n" +
	"\x10contract_version\x18\x01 \x01(\rR\x0fcontractVersion\x12\x19\n" +
	"\bshell_id\x18\x02 \x01(\tR\ashellId\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\"\xb6\x01\n" +
	"\fHolderReplay\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x04R\x04from\x12\x12\n" +
	"\x04lost\x18\x03 \x01(\x04R\x04lost\x12\x16\n" +
	"\x06exited\x18\x04 \x01(\bR\x06exited\x12\x12\n" +
	"\x04code\x18\x05 \x01(\x05R\x04code\x12\x16\n" +
	"\x06screen\x18\x06 \x01(\fR\x06screen\x12\x12\n" +
	"\x04cols\x18\a \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\b \x01(\rR\x04rowsB?Z=github.com/nghyane/tilder/go/internal/wire/tilder/v1;tilderv1b\x06proto3"

var (
	file_tilder_v1_holder_proto_rawDescOnce sync.Once
	file_tilder_v1_holder_proto_rawDescData []byte
)

func file_tilder_v1_holder_proto_rawDescGZIP() []byte {
	file_tilder_v1_holder_proto_rawDescOnce.Do(func() {
		file_tilder_v1_holder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tilder_v1_holder_proto_rawDesc), len(file_tilder_v1_holder_proto_rawDesc)))
	})
	return file_tilder_v1_holder_proto_rawDescData
}

var file_tilder_v1_holder_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tilder_v1_holder_proto_goTypes = []any{
	(*HolderRequest)(nil), // 0: tilder.v1.HolderRequest
	(*HolderHello)(nil),   // 1: tilder.v1.HolderHello
	(*HolderAttach)(nil),  // 2: tilder.v1.HolderAttach
	(*HolderEvent)(nil),   // 3: tilder.v1.HolderEvent
	(*HolderWelcome)(nil), // 4: tilder.v1.HolderWelcome
	(*HolderReplay)(nil),  // 5: tilder.v1.HolderReplay
	(*PtyInput)(nil),      // 6: tilder.v1.PtyInput
	(*Resize)(nil),        // 7: tilder.v1.Resize
	(*Kill)(nil),          // 8: tilder.v1.Kill
	(*Output)(nil),        // 9: tilder.v1.Output
	(*Exit)(nil),          // 10: tilder.v1.Exit
}
var file_tilder_v1_holder_proto_depIdxs = []int32{
	1,  // 0: tilder.v1.HolderRequest.hello:type_name -> tilder.v1.HolderHello
	2,  // 1: tilder.v1.HolderRequest.attach:type_name -> tilder.v1.HolderAttach
	6,  // 2: tilder.v1.HolderRequest.input:type_name -> tilder.v1.PtyInput
	7,  // 3: tilder.v1.HolderRequest.resize:type_name -> tilder.v1.Resize
	8,  // 4: tilder.v1.HolderRequest.kill:type_name -> tilder.v1.Kill
	4,  // 5: tilder.v1.HolderEvent.welcome:type_name -> tilder.v1.HolderWelcome
	5,  // 6: tilder.v1.HolderEvent.replay:type_name -> tilder.v1.HolderReplay
	9,  // 7: tilder.v1.HolderEvent.output:type_name -> tilder.v1.Output
	10, // 8: tilder.v1.HolderEvent.exit:type_name -> tilder.v1.Exit
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_tilder_v1_holder_proto_init() }
func file_tilder_v1_holder_proto_init() {
	if File_tilder_v1_holder_proto != nil {
		return
	}
	file_tilder_v1_pty_proto_init()
	file_tilder_v1_holder_proto_msgTypes[0].OneofWrappers = []any{
		(*HolderRequest_Hello)(nil),
		(*HolderRequest_Attach)(nil),
		(*HolderRequest_Input)(nil),
		(*HolderRequest_Resize)(nil),
		(*HolderRequest_Kill)(nil),
	}
	file_tilder_v1_holder_proto_msgTypes[3].OneofWrappers = []any{
		(*HolderEvent_Welcome)(nil),
		(*HolderEvent_Replay)(nil),
		(*HolderEvent_Output)(nil),
		(*HolderEvent_Exit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tilder_v1_holder_proto_rawDesc), len(file_tilder_v1_holder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tilder_v1_holder_proto_goTypes,
		DependencyIndexes: file_tilder_v1_holder_proto_depIdxs,
		MessageInfos:      file_tilder_v1_holder_proto_msgTypes,
	}.Build()
	File_tilder_v1_holder_proto = out.File
	file_tilder_v1_holder_proto_goTypes = nil
	file_tilder_v1_holder_proto_depIdxs = nil
}
