// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: tilder/v1/pty.proto

// One shell over the `pty` DataChannel (PROTOCOL §4). Offsets count wire
// bytes, never characters.

package tilderv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PtyRefused_Code int32

const (
	PtyRefused_CODE_UNSPECIFIED PtyRefused_Code = 0
	PtyRefused_CODE_NOT_FOUND   PtyRefused_Code = 1
	PtyRefused_CODE_NOT_DIR     PtyRefused_Code = 2
	PtyRefused_CODE_DENIED      PtyRefused_Code = 3
	PtyRefused_CODE_INVALID     PtyRefused_Code = 4
)

// Enum value maps for PtyRefused_Code.
var (
	PtyRefused_Code_name = map[int32]string{
		0: "CODE_UNSPECIFIED",
		1: "CODE_NOT_FOUND",
		2: "CODE_NOT_DIR",
		3: "CODE_DENIED",
		4: "CODE_INVALID",
	}
	PtyRefused_Code_value = map[string]int32{
		"CODE_UNSPECIFIED": 0,
		"CODE_NOT_FOUND":   1,
		"CODE_NOT_DIR":     2,
		"CODE_DENIED":      3,
		"CODE_INVALID":     4,
	}
)

func (x PtyRefused_Code) Enum() *PtyRefused_Code {
	p := new(PtyRefused_Code)
	*p = x
	return p
}

func (x PtyRefused_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PtyRefused_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_tilder_v1_pty_proto_enumTypes[0].Descriptor()
}

func (PtyRefused_Code) Type() protoreflect.EnumType {
	return &file_tilder_v1_pty_proto_enumTypes[0]
}

func (x PtyRefused_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PtyRefused_Code.Descriptor instead.
func (PtyRefused_Code) EnumDescriptor() ([]byte, []int) {
	return file_tilder_v1_pty_proto_rawDescGZIP(), []int{11, 0}
}

type PtyClient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*PtyClient_Attach
	//	*PtyClient_Input
	//	*PtyClient_Resize
	//	*PtyClient_Ack
	//	*PtyClient_Kill
	//	*PtyClient_Claim
	Msg           isPtyClient_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtyClient) Reset() {
	*x = PtyClient{}
	mi := &file_tilder_v1_pty_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtyClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyClient) ProtoMessage() {}

func (x *PtyClient) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_pty_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyClient.ProtoReflect.Descriptor instead.
func (*PtyClient) Descriptor() ([]byte, []int) {
	return file_tilder_v1_pty_proto_rawDescGZIP(), []int{0}
}

func (x *PtyClient) GetMsg() isPtyClient_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *PtyClient) GetAttach() *Attach {
	if x != nil {
		if x, ok := x.Msg.(*PtyClient_Attach); ok {
			return x.Attach
		}
	}
	return nil
}

func (x *PtyClient) GetInput() *PtyInput {
	if x != nil {
		if x, ok := x.Msg.(*PtyClient_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *PtyClient) GetResize() *Resize {
	if x != nil {
		if x, ok := x.Msg.(*PtyClient_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

func (x *PtyClient) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Msg.(*PtyClient_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *PtyClient) GetKill() *Kill {
	if x != nil {
		if x, ok := x.Msg.(*PtyClient_Kill); ok {
			return x.Kill
		}
	}
	return nil
}

func (x *PtyClient) GetClaim() *Claim {
	if x != nil {
		if x, ok := x.Msg.(*PtyClient_Claim); ok {
			return x.Claim
		}
	}
	return nil
}

type isPtyClient_Msg interface {
	isPtyClient_Msg()
}

type PtyClient_Attach struct {
	Attach *Attach `protobuf:"bytes,1,opt,name=attach,proto3,oneof"`
}

type PtyClient_Input struct {
	Input *PtyInput `protobuf:"bytes,2,opt,name=input,proto3,oneof"`
}

type PtyClient_Resize struct {
	Resize *Resize `protobuf:"bytes,3,opt,name=resize,proto3,oneof"`
}

type PtyClient_Ack struct {
	Ack *Ack `protobuf:"bytes,4,opt,name=ack,proto3,oneof"`
}

type PtyClient_Kill struct {
	Kill *Kill `protobuf:"bytes,5,opt,name=kill,proto3,oneof"`
}

type PtyClient_Claim struct {
	Claim *Claim `protobuf:"bytes,6,opt,name=claim,proto3,oneof"`
}

func (*PtyClient_Attach) isPtyClient_Msg() {}

func (*PtyClient_Input) isPtyClient_Msg() {}

func (*PtyClient_Resize) isPtyClient_Msg() {}

func (*PtyClient_Ack) isPtyClient_Msg() {}

func (*PtyClient_Kill) isPtyClient_Msg() {}

func (*PtyClient_Claim) isPtyClient_Msg() {}

type PtyServer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*PtyServer_Output
	//	*PtyServer_Exit
	//	*PtyServer_Screen
	//	*PtyServer_Refused
	//	*PtyServer_Cwd
	//	*PtyServer_Size
	Msg           isPtyServer_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtyServer) Reset() {
	*x = PtyServer{}
	mi := &file_tilder_v1_pty_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtyServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyServer) ProtoMessage() {}

func (x *PtyServer) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_pty_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyServer.ProtoReflect.Descriptor instead.
func (*PtyServer) Descriptor() ([]byte, []int) {
	return file_tilder_v1_pty_proto_rawDescGZIP(), []int{1}
}

func (x *PtyServer) GetMsg() isPtyServer_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *PtyServer) GetOutput() *Output {
	if x != nil {
		if x, ok := x.Msg.(*PtyServer_Output); ok {
			return x.Output
		}
	}
	return nil
}

func (x *PtyServer) GetExit() *Exit {
	if x != nil {
		if x, ok := x.Msg.(*PtyServer_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

func (x *PtyServer) GetScreen() *Screen {
	if x != nil {
		if x, ok := x.Msg.(*PtyServer_Screen); ok {
			return x.Screen
		}
	}
	return nil
}

func (x *PtyServer) GetRefused() *PtyRefused {
	if x != nil {
		if x, ok := x.Msg.(*PtyServer_Refused); ok {
			return x.Refused
		}
	}
	return nil
}

func (x *PtyServer) GetCwd() *PtyCwd {
	if x != nil {
		if x, ok := x.Msg.(*PtyServer_Cwd); ok {
			return x.Cwd
		}
	}
	return nil
}

func (x *PtyServer) GetSize() *Resize {
	if x != nil {
		if x, ok := x.Msg.(*PtyServer_Size); ok {
			return x.Size
		}
	}
	return nil
}

type isPtyServer_Msg interface {
	isPtyServer_Msg()
}

type PtyServer_Output struct {
	Output *Output `protobuf:"bytes,1,opt,name=output,proto3,oneof"`
}

type PtyServer_Exit struct {
	Exit *Exit `protobuf:"bytes,2,opt,name=exit,proto3,oneof"`
}

type PtyServer_Screen struct {
	Screen *Screen `protobuf:"bytes,3,opt,name=screen,proto3,oneof"`
}

type PtyServer_Refused struct {
	Refused *PtyRefused `protobuf:"bytes,4,opt,name=refused,proto3,oneof"`
}

type PtyServer_Cwd struct {
	Cwd *PtyCwd `protobuf:"bytes,5,opt,name=cwd,proto3,oneof"`
}

type PtyServer_Size struct {
	// The shell's size now (ADR 0033): after the attach, and whenever the
	// device that decides it changes. It may not be the size this client
	// asked for; the client draws at this size and does not send it back.
	Size *Resize `protobuf:"bytes,6,opt,name=size,proto3,oneof"`
}

func (*PtyServer_Output) isPtyServer_Msg() {}

func (*PtyServer_Exit) isPtyServer_Msg() {}

func (*PtyServer_Screen) isPtyServer_Msg() {}

func (*PtyServer_Refused) isPtyServer_Msg() {}

func (*PtyServer_Cwd) isPtyServer_Msg() {}

func (*PtyServer_Size) isPtyServer_Msg() {}

type Attach struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ShellId string                 `protobuf:"bytes,1,opt,name=shell_id,json=shellId,proto3" json:"shell_id,omitempty"`
	Since   uint64                 `protobuf:"varint,2,opt,name=since,proto3" json:"since,omitempty"`
	Cols    uint32                 `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows    uint32                 `protobuf:"varint,4,opt,name=rows,proto3" json:"rows,omitempty"`
	// Unacknowledged bytes the client accepts; the agent clamps it to [16 KiB, 1 MiB].
	Window uint32 `protobuf:"varint,5,opt,name=window,proto3" json:"window,omitempty"`
	// Where a new shell starts: a path under the home, as the fs channel takes
	// it (ADR 0024). Empty is the home. Ignored when the shell already runs.
	Dir           []byte `protobuf:"bytes,6,opt,name=dir,proto3" json:"dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attach) Reset() {
	*x = Attach{}
	mi := &file_tilder_v1_pty_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attach) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attach) ProtoMessage() {}

func (x *Attach) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_pty_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attach.ProtoReflect.Descriptor instead.
func (*Attach) Descriptor() ([]byte, []int) {
	return file_tilder_v1_pty_proto_rawDescGZIP(), []int{2}
}

func (x *Attach) GetShellId() string {
	if x != nil {
		return x.ShellId
	}
	return ""
}

func (x *Attach) GetSince() uint64 {
	if x != nil {
		return x.Since
	}
	return 0
}

func (x *Attach) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Attach) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Attach) GetWindow() uint32 {
	if x != nil {
		return x.Window
	}
	return 0
}

func (x *Attach) GetDir() []byte {
	if x != nil {
		return x.Dir
	}
	return nil
}

type PtyInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtyInput) Reset() {
	*x = PtyInput{}
	mi := &file_tilder_v1_pty_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtyInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyInput) ProtoMessage() {}

func (x *PtyInput) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_pty_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyInput.ProtoReflect.Descriptor instead.
func (*PtyInput) Descriptor() ([]byte, []int) {
	return file_tilder_v1_pty_proto_rawDescGZIP(), []int{3}
}

func (x *PtyInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Resize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          uint32                 `protobuf:"varint,1,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resize) Reset() {
	*x = Resize{}
	mi := &file_tilder_v1_pty_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resize) ProtoMessage() {}

func (x *Resize) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_pty_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resize.ProtoReflect.Descriptor instead.
func (*Resize) Descriptor() ([]byte, []int) {
	return file_tilder_v1_pty_proto_rawDescGZIP(), []int{4}
}

func (x *Resize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Resize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_tilder_v1_pty_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_pty_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_tilder_v1_pty_proto_rawDescGZIP(), []int{5}
}

func (x *Ack) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// Ends the shell and everything in its session (ADR 0014): the tab was closed.
type Kill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kill) Reset() {
	*x = Kill{}
	mi := &file_tilder_v1_pty_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kill) ProtoMessage() {}

func (x *Kill) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_pty_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kill.ProtoReflect.Descriptor instead.
func (*Kill) Descriptor() ([]byte, []int) {
	return file_tilder_v1_pty_proto_rawDescGZIP(), []int{6}
}

// Takes the shell's size for this client without typing (ADR 0033): as a
// keystroke would, but nothing reaches the shell.
type Claim struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Claim) Reset() {
	*x = Claim{}
	mi := &file_tilder_v1_pty_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Claim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claim) ProtoMessage() {}

func (x *Claim) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_pty_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claim.ProtoReflect.Descriptor instead.
func (*Claim) Descriptor() ([]byte, []int) {
	return file_tilder_v1_pty_proto_rawDescGZIP(), []int{7}
}

type Output struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Seq   uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Data  []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Catch-up from the ring at attach, not live output (ADR 0015). The
	// console writes it without answering the terminal queries inside: the
	// program that asked stopped waiting long ago.
	Replay        bool `protobuf:"varint,3,opt,name=replay,proto3" json:"replay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Output) Reset() {
	*x = Output{}
	mi := &file_tilder_v1_pty_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Output) ProtoMessage() {}

func (x *Output) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_pty_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Output.ProtoReflect.Descriptor instead.
func (*Output) Descriptor() ([]byte, []int) {
	return file_tilder_v1_pty_proto_rawDescGZIP(), []int{8}
}

func (x *Output) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Output) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Output) GetReplay() bool {
	if x != nil {
		return x.Replay
	}
	return false
}

// The screen as the shell drew it (ADR 0017), sent at an attach from 0
// instead of the history, which was drawn at other sizes and may have
// scrolled out of the ring. A long screen comes in parts, in order: the first
// has cols and rows (reset the terminal to that size, then write), the last
// has `last` (fit the terminal to its pane again; the program redraws). The
// data counts no offsets: output goes on from `seq`.
type Screen struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	Rows          uint32                 `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	Seq           uint64                 `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	Last          bool                   `protobuf:"varint,5,opt,name=last,proto3" json:"last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Screen) Reset() {
	*x = Screen{}
	mi := &file_tilder_v1_pty_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Screen) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Screen) ProtoMessage() {}

func (x *Screen) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_pty_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Screen.ProtoReflect.Descriptor instead.
func (*Screen) Descriptor() ([]byte, []int) {
	return file_tilder_v1_pty_proto_rawDescGZIP(), []int{9}
}

func (x *Screen) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Screen) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *Screen) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *Screen) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Screen) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

type Exit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Exit) Reset() {
	*x = Exit{}
	mi := &file_tilder_v1_pty_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Exit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Exit) ProtoMessage() {}

func (x *Exit) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_pty_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Exit.ProtoReflect.Descriptor instead.
func (*Exit) Descriptor() ([]byte, []int) {
	return file_tilder_v1_pty_proto_rawDescGZIP(), []int{10}
}

func (x *Exit) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

// The attach was refused, and why; the channel closes after it (ADR 0024).
type PtyRefused struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          PtyRefused_Code        `protobuf:"varint,1,opt,name=code,proto3,enum=tilder.v1.PtyRefused_Code" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtyRefused) Reset() {
	*x = PtyRefused{}
	mi := &file_tilder_v1_pty_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtyRefused) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyRefused) ProtoMessage() {}

func (x *PtyRefused) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_pty_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyRefused.ProtoReflect.Descriptor instead.
func (*PtyRefused) Descriptor() ([]byte, []int) {
	return file_tilder_v1_pty_proto_rawDescGZIP(), []int{11}
}

func (x *PtyRefused) GetCode() PtyRefused_Code {
	if x != nil {
		return x.Code
	}
	return PtyRefused_CODE_UNSPECIFIED
}

// The folder the shell is in now (ADR 0024): its process's working
// directory, looked up after output, at most every 2 s, sent when it
// changes. `dir` is relative to the home, as the fs channel takes it; a
// folder outside the home comes absolute with `outside_home`, to be shown,
// never to start a shell in.
type PtyCwd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dir           []byte                 `protobuf:"bytes,1,opt,name=dir,proto3" json:"dir,omitempty"`
	OutsideHome   bool                   `protobuf:"varint,2,opt,name=outside_home,json=outsideHome,proto3" json:"outside_home,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PtyCwd) Reset() {
	*x = PtyCwd{}
	mi := &file_tilder_v1_pty_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PtyCwd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PtyCwd) ProtoMessage() {}

func (x *PtyCwd) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_pty_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PtyCwd.ProtoReflect.Descriptor instead.
func (*PtyCwd) Descriptor() ([]byte, []int) {
	return file_tilder_v1_pty_proto_rawDescGZIP(), []int{12}
}

func (x *PtyCwd) GetDir() []byte {
	if x != nil {
		return x.Dir
	}
	return nil
}

func (x *PtyCwd) GetOutsideHome() bool {
	if x != nil {
		return x.OutsideHome
	}
	return false
}

var File_tilder_v1_pty_proto protoreflect.FileDescriptor

const file_tilder_v1_pty_proto_rawDesc = "" +
	"\n" +
	"\x13tilder/v1/pty.proto\x12\ttilder.v1\"\x8e\x02\n" +
	"\tPtyClient\x12+\n" +
	"\x06attach\x18\x01 \x01(\v2\x11.tilder.v1.AttachH\x00R\x06attach\x12+\n" +
	"\x05input\x18\x02 \x01(\v2\x13.tilder.v1.PtyInputH\x00R\x05input\x12+\n" +
	"\x06resize\x18\x03 \x01(\v2\x11.tilder.v1.ResizeH\x00R\x06resize\x12\"\n" +
	"\x03ack\x18\x04 \x01(\v2\x0e.tilder.v1.AckH\x00R\x03ack\x12%\n" +
	"\x04kill\x18\x05 \x01(\v2\x0f.tilder.v1.KillH\x00R\x04kill\x12(\n" +
	"\x05claim\x18\x06 \x01(\v2\x10.tilder.v1.ClaimH\x00R\x05claimB\x05\n" +
	"\x03msg\"\x96\x02\n" +
	"\tPtyServer\x12+\n" +
	"\x06output\x18\x01 \x01(\v2\x11.tilder.v1.OutputH\x00R\x06output\x12%\n" +
	"\x04exit\x18\x02 \x01(\v2\x0f.tilder.v1.ExitH\x00R\x04exit\x12+\n" +
	"\x06screen\x18\x03 \x01(\v2\x11.tilder.v1.ScreenH\x00R\x06screen\x121\n" +
	"\arefused\x18\x04 \x01(\v2\x15.tilder.v1.PtyRefusedH\x00R\arefused\x12%\n" +
	"\x03cwd\x18\x05 \x01(\v2\x11.tilder.v1.PtyCwdH\x00R\x03cwd\x12'\n" +
	"\x04size\x18\x06 \x01(\v2\x11.tilder.v1.ResizeH\x00R\x04sizeB\x05\n" +
	"\x03msg\"\x8b\x01\n" +
	"\x06Attach\x12\x19\n" +
	"\bshell_id\x18\x01 \x01(\tR\ashellId\x12\x14\n" +
	"\x05since\x18\x02 \x01(\x04R\x05since\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x04 \x01(\rR\x04rows\x12\x16\n" +
	"\x06window\x18\x05 \x01(\rR\x06window\x12\x10\n" +
	"\x03dir\x18\x06 \x01(\fR\x03dir\"\x1e\n" +
	"\bPtyInput\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"0\n" +
	"\x06Resize\x12\x12\n" +
	"\x04cols\x18\x01 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\rR\x04rows\"\x17\n" +
	"\x03Ack\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\"\x06\n" +
	"\x04Kill\"\a\n" +
	"\x05Claim\"F\n" +
	"\x06Output\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x16\n" +
	"\x06replay\x18\x03 \x01(\bR\x06replay\"j\n" +
	"\x06Screen\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols\x12\x12\n" +
	"\x04rows\x18\x03 \x01(\rR\x04rows\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x04R\x03seq\x12\x12\n" +
	"\x04last\x18\x05 \x01(\bR\x04last\"\x1a\n" +
	"\x04Exit\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\"\xa3\x01\n" +
	"\n" +
	"PtyRefused\x12.\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1a.tilder.v1.PtyRefused.CodeR\x04code\"e\n" +
	"\x04Code\x12\x14\n" +
	"\x10CODE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eCODE_NOT_FOUND\x10\x01\x12\x10\n" +
	"\fCODE_NOT_DIR\x10\x02\x12\x0f\n" +
	"\vCODE_DENIED\x10\x03\x12\x10\n" +
	"\fCODE_INVALID\x10\x04\"=\n" +
	"\x06PtyCwd\x12\x10\n" +
	"\x03dir\x18\x01 \x01(\fR\x03dir\x12!\n" +
	"\foutside_home\x18\x02 \x01(\bR\voutsideHomeB?Z=github.com/nghyane/tilder/go/internal/wire/tilder/v1;tilderv1b\x06proto3"

var (
	file_tilder_v1_pty_proto_rawDescOnce sync.Once
	file_tilder_v1_pty_proto_rawDescData []byte
)

func file_tilder_v1_pty_proto_rawDescGZIP() []byte {
	file_tilder_v1_pty_proto_rawDescOnce.Do(func() {
		file_tilder_v1_pty_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tilder_v1_pty_proto_rawDesc), len(file_tilder_v1_pty_proto_rawDesc)))
	})
	return file_tilder_v1_pty_proto_rawDescData
}

var file_tilder_v1_pty_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tilder_v1_pty_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_tilder_v1_pty_proto_goTypes = []any{
	(PtyRefused_Code)(0), // 0: tilder.v1.PtyRefused.Code
	(*PtyClient)(nil),    // 1: tilder.v1.PtyClient
	(*PtyServer)(nil),    // 2: tilder.v1.PtyServer
	(*Attach)(nil),       // 3: tilder.v1.Attach
	(*PtyInput)(nil),     // 4: tilder.v1.PtyInput
	(*Resize)(nil),       // 5: tilder.v1.Resize
	(*Ack)(nil),          // 6: tilder.v1.Ack
	(*Kill)(nil),         // 7: tilder.v1.Kill
	(*Claim)(nil),        // 8: tilder.v1.Claim
	(*Output)(nil),       // 9: tilder.v1.Output
	(*Screen)(nil),       // 10: tilder.v1.Screen
	(*Exit)(nil),         // 11: tilder.v1.Exit
	(*PtyRefused)(nil),   // 12: tilder.v1.PtyRefused
	(*PtyCwd)(nil),       // 13: tilder.v1.PtyCwd
}
var file_tilder_v1_pty_proto_depIdxs = []int32{
	3,  // 0: tilder.v1.PtyClient.attach:type_name -> tilder.v1.Attach
	4,  // 1: tilder.v1.PtyClient.input:type_name -> tilder.v1.PtyInput
	5,  // 2: tilder.v1.PtyClient.resize:type_name -> tilder.v1.Resize
	6,  // 3: tilder.v1.PtyClient.ack:type_name -> tilder.v1.Ack
	7,  // 4: tilder.v1.PtyClient.kill:type_name -> tilder.v1.Kill
	8,  // 5: tilder.v1.PtyClient.claim:type_name -> tilder.v1.Claim
	9,  // 6: tilder.v1.PtyServer.output:type_name -> tilder.v1.Output
	11, // 7: tilder.v1.PtyServer.exit:type_name -> tilder.v1.Exit
	10, // 8: tilder.v1.PtyServer.screen:type_name -> tilder.v1.Screen
	12, // 9: tilder.v1.PtyServer.refused:type_name -> tilder.v1.PtyRefused
	13, // 10: tilder.v1.PtyServer.cwd:type_name -> tilder.v1.PtyCwd
	5,  // 11: tilder.v1.PtyServer.size:type_name -> tilder.v1.Resize
	0,  // 12: tilder.v1.PtyRefused.code:type_name -> tilder.v1.PtyRefused.Code
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_tilder_v1_pty_proto_init() }
func file_tilder_v1_pty_proto_init() {
	if File_tilder_v1_pty_proto != nil {
		return
	}
	file_tilder_v1_pty_proto_msgTypes[0].OneofWrappers = []any{
		(*PtyClient_Attach)(nil),
		(*PtyClient_Input)(nil),
		(*PtyClient_Resize)(nil),
		(*PtyClient_Ack)(nil),
		(*PtyClient_Kill)(nil),
		(*PtyClient_Claim)(nil),
	}
	file_tilder_v1_pty_proto_msgTypes[1].OneofWrappers = []any{
		(*PtyServer_Output)(nil),
		(*PtyServer_Exit)(nil),
		(*PtyServer_Screen)(nil),
		(*PtyServer_Refused)(nil),
		(*PtyServer_Cwd)(nil),
		(*PtyServer_Size)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tilder_v1_pty_proto_rawDesc), len(file_tilder_v1_pty_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tilder_v1_pty_proto_goTypes,
		DependencyIndexes: file_tilder_v1_pty_proto_depIdxs,
		EnumInfos:         file_tilder_v1_pty_proto_enumTypes,
		MessageInfos:      file_tilder_v1_pty_proto_msgTypes,
	}.Build()
	File_tilder_v1_pty_proto = out.File
	file_tilder_v1_pty_proto_goTypes = nil
	file_tilder_v1_pty_proto_depIdxs = nil
}
