// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: tilder/v1/xfer.proto

// Copies between machines (ADR 0035), on two DataChannels.
//
// `xfer-ctl`: a device asks the destination machine to pull (on the device's
// own connection to that machine). Every message carries its request's id;
// progress for a copy comes on the id of the Pull that started it.
//
// `xfer`: the destination machine pulls from the source machine, on a
// connection the destination opened for one grant. The source serves only
// what that grant names, read-only. Chunks are 1 MiB for hashing and
// resuming; each travels as pieces of at most 15 KiB (ADR 0022: messages
// under 16 KiB), then its hash.

package tilderv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type XferRoute int32

const (
	XferRoute_XFER_ROUTE_UNSPECIFIED XferRoute = 0
	XferRoute_XFER_ROUTE_DIRECT      XferRoute = 1
	XferRoute_XFER_ROUTE_RELAYED     XferRoute = 2
)

// Enum value maps for XferRoute.
var (
	XferRoute_name = map[int32]string{
		0: "XFER_ROUTE_UNSPECIFIED",
		1: "XFER_ROUTE_DIRECT",
		2: "XFER_ROUTE_RELAYED",
	}
	XferRoute_value = map[string]int32{
		"XFER_ROUTE_UNSPECIFIED": 0,
		"XFER_ROUTE_DIRECT":      1,
		"XFER_ROUTE_RELAYED":     2,
	}
)

func (x XferRoute) Enum() *XferRoute {
	p := new(XferRoute)
	*p = x
	return p
}

func (x XferRoute) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (XferRoute) Descriptor() protoreflect.EnumDescriptor {
	return file_tilder_v1_xfer_proto_enumTypes[0].Descriptor()
}

func (XferRoute) Type() protoreflect.EnumType {
	return &file_tilder_v1_xfer_proto_enumTypes[0]
}

func (x XferRoute) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use XferRoute.Descriptor instead.
func (XferRoute) EnumDescriptor() ([]byte, []int) {
	return file_tilder_v1_xfer_proto_rawDescGZIP(), []int{0}
}

type XferFailed_Code int32

const (
	XferFailed_CODE_UNSPECIFIED XferFailed_Code = 0
	XferFailed_CODE_DENIED      XferFailed_Code = 1
	XferFailed_CODE_UNREACHABLE XferFailed_Code = 2
	XferFailed_CODE_NOT_FOUND   XferFailed_Code = 3
	XferFailed_CODE_NO_SPACE    XferFailed_Code = 4
	XferFailed_CODE_CHANGED     XferFailed_Code = 5
	XferFailed_CODE_CANCELLED   XferFailed_Code = 6
	XferFailed_CODE_EXPIRED     XferFailed_Code = 7
	XferFailed_CODE_INTERNAL    XferFailed_Code = 8
	// More entries than one copy may hold: copy a folder further down.
	XferFailed_CODE_TOO_LARGE XferFailed_Code = 9
)

// Enum value maps for XferFailed_Code.
var (
	XferFailed_Code_name = map[int32]string{
		0: "CODE_UNSPECIFIED",
		1: "CODE_DENIED",
		2: "CODE_UNREACHABLE",
		3: "CODE_NOT_FOUND",
		4: "CODE_NO_SPACE",
		5: "CODE_CHANGED",
		6: "CODE_CANCELLED",
		7: "CODE_EXPIRED",
		8: "CODE_INTERNAL",
		9: "CODE_TOO_LARGE",
	}
	XferFailed_Code_value = map[string]int32{
		"CODE_UNSPECIFIED": 0,
		"CODE_DENIED":      1,
		"CODE_UNREACHABLE": 2,
		"CODE_NOT_FOUND":   3,
		"CODE_NO_SPACE":    4,
		"CODE_CHANGED":     5,
		"CODE_CANCELLED":   6,
		"CODE_EXPIRED":     7,
		"CODE_INTERNAL":    8,
		"CODE_TOO_LARGE":   9,
	}
)

func (x XferFailed_Code) Enum() *XferFailed_Code {
	p := new(XferFailed_Code)
	*p = x
	return p
}

func (x XferFailed_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (XferFailed_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_tilder_v1_xfer_proto_enumTypes[1].Descriptor()
}

func (XferFailed_Code) Type() protoreflect.EnumType {
	return &file_tilder_v1_xfer_proto_enumTypes[1]
}

func (x XferFailed_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use XferFailed_Code.Descriptor instead.
func (XferFailed_Code) EnumDescriptor() ([]byte, []int) {
	return file_tilder_v1_xfer_proto_rawDescGZIP(), []int{8, 0}
}

type XferCtlClient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	ReqId uint32                 `protobuf:"varint,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*XferCtlClient_Pull
	//	*XferCtlClient_List
	//	*XferCtlClient_Cancel
	Msg           isXferCtlClient_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XferCtlClient) Reset() {
	*x = XferCtlClient{}
	mi := &file_tilder_v1_xfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XferCtlClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XferCtlClient) ProtoMessage() {}

func (x *XferCtlClient) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_xfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XferCtlClient.ProtoReflect.Descriptor instead.
func (*XferCtlClient) Descriptor() ([]byte, []int) {
	return file_tilder_v1_xfer_proto_rawDescGZIP(), []int{0}
}

func (x *XferCtlClient) GetReqId() uint32 {
	if x != nil {
		return x.ReqId
	}
	return 0
}

func (x *XferCtlClient) GetMsg() isXferCtlClient_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *XferCtlClient) GetPull() *XferPull {
	if x != nil {
		if x, ok := x.Msg.(*XferCtlClient_Pull); ok {
			return x.Pull
		}
	}
	return nil
}

func (x *XferCtlClient) GetList() *XferList {
	if x != nil {
		if x, ok := x.Msg.(*XferCtlClient_List); ok {
			return x.List
		}
	}
	return nil
}

func (x *XferCtlClient) GetCancel() *XferCancel {
	if x != nil {
		if x, ok := x.Msg.(*XferCtlClient_Cancel); ok {
			return x.Cancel
		}
	}
	return nil
}

type isXferCtlClient_Msg interface {
	isXferCtlClient_Msg()
}

type XferCtlClient_Pull struct {
	Pull *XferPull `protobuf:"bytes,2,opt,name=pull,proto3,oneof"`
}

type XferCtlClient_List struct {
	List *XferList `protobuf:"bytes,3,opt,name=list,proto3,oneof"`
}

type XferCtlClient_Cancel struct {
	Cancel *XferCancel `protobuf:"bytes,4,opt,name=cancel,proto3,oneof"`
}

func (*XferCtlClient_Pull) isXferCtlClient_Msg() {}

func (*XferCtlClient_List) isXferCtlClient_Msg() {}

func (*XferCtlClient_Cancel) isXferCtlClient_Msg() {}

type XferCtlServer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	ReqId uint32                 `protobuf:"varint,1,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*XferCtlServer_Accepted
	//	*XferCtlServer_Progress
	//	*XferCtlServer_Done
	//	*XferCtlServer_Failed
	//	*XferCtlServer_Jobs
	Msg           isXferCtlServer_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XferCtlServer) Reset() {
	*x = XferCtlServer{}
	mi := &file_tilder_v1_xfer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XferCtlServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XferCtlServer) ProtoMessage() {}

func (x *XferCtlServer) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_xfer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XferCtlServer.ProtoReflect.Descriptor instead.
func (*XferCtlServer) Descriptor() ([]byte, []int) {
	return file_tilder_v1_xfer_proto_rawDescGZIP(), []int{1}
}

func (x *XferCtlServer) GetReqId() uint32 {
	if x != nil {
		return x.ReqId
	}
	return 0
}

func (x *XferCtlServer) GetMsg() isXferCtlServer_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *XferCtlServer) GetAccepted() *XferAccepted {
	if x != nil {
		if x, ok := x.Msg.(*XferCtlServer_Accepted); ok {
			return x.Accepted
		}
	}
	return nil
}

func (x *XferCtlServer) GetProgress() *XferProgress {
	if x != nil {
		if x, ok := x.Msg.(*XferCtlServer_Progress); ok {
			return x.Progress
		}
	}
	return nil
}

func (x *XferCtlServer) GetDone() *XferDone {
	if x != nil {
		if x, ok := x.Msg.(*XferCtlServer_Done); ok {
			return x.Done
		}
	}
	return nil
}

func (x *XferCtlServer) GetFailed() *XferFailed {
	if x != nil {
		if x, ok := x.Msg.(*XferCtlServer_Failed); ok {
			return x.Failed
		}
	}
	return nil
}

func (x *XferCtlServer) GetJobs() *XferJobs {
	if x != nil {
		if x, ok := x.Msg.(*XferCtlServer_Jobs); ok {
			return x.Jobs
		}
	}
	return nil
}

type isXferCtlServer_Msg interface {
	isXferCtlServer_Msg()
}

type XferCtlServer_Accepted struct {
	Accepted *XferAccepted `protobuf:"bytes,2,opt,name=accepted,proto3,oneof"`
}

type XferCtlServer_Progress struct {
	Progress *XferProgress `protobuf:"bytes,3,opt,name=progress,proto3,oneof"`
}

type XferCtlServer_Done struct {
	Done *XferDone `protobuf:"bytes,4,opt,name=done,proto3,oneof"`
}

type XferCtlServer_Failed struct {
	Failed *XferFailed `protobuf:"bytes,5,opt,name=failed,proto3,oneof"`
}

type XferCtlServer_Jobs struct {
	Jobs *XferJobs `protobuf:"bytes,6,opt,name=jobs,proto3,oneof"`
}

func (*XferCtlServer_Accepted) isXferCtlServer_Msg() {}

func (*XferCtlServer_Progress) isXferCtlServer_Msg() {}

func (*XferCtlServer_Done) isXferCtlServer_Msg() {}

func (*XferCtlServer_Failed) isXferCtlServer_Msg() {}

func (*XferCtlServer_Jobs) isXferCtlServer_Msg() {}

// Pull what the grant names into the destination. The destination refuses a
// grant not for itself, not from its owner's device, removed, or out of date.
type XferPull struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grant         *TransferGrant         `protobuf:"bytes,1,opt,name=grant,proto3" json:"grant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XferPull) Reset() {
	*x = XferPull{}
	mi := &file_tilder_v1_xfer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XferPull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XferPull) ProtoMessage() {}

func (x *XferPull) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_xfer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XferPull.ProtoReflect.Descriptor instead.
func (*XferPull) Descriptor() ([]byte, []int) {
	return file_tilder_v1_xfer_proto_rawDescGZIP(), []int{2}
}

func (x *XferPull) GetGrant() *TransferGrant {
	if x != nil {
		return x.Grant
	}
	return nil
}

// The copies this machine holds, running or ended not long ago: a tab opened
// again shows them.
type XferList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XferList) Reset() {
	*x = XferList{}
	mi := &file_tilder_v1_xfer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XferList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XferList) ProtoMessage() {}

func (x *XferList) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_xfer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XferList.ProtoReflect.Descriptor instead.
func (*XferList) Descriptor() ([]byte, []int) {
	return file_tilder_v1_xfer_proto_rawDescGZIP(), []int{3}
}

type XferCancel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The copy's id (the grant's nonce, base64url).
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XferCancel) Reset() {
	*x = XferCancel{}
	mi := &file_tilder_v1_xfer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XferCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XferCancel) ProtoMessage() {}

func (x *XferCancel) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_xfer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XferCancel.ProtoReflect.Descriptor instead.
func (*XferCancel) Descriptor() ([]byte, []int) {
	return file_tilder_v1_xfer_proto_rawDescGZIP(), []int{4}
}

func (x *XferCancel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type XferAccepted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XferAccepted) Reset() {
	*x = XferAccepted{}
	mi := &file_tilder_v1_xfer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XferAccepted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XferAccepted) ProtoMessage() {}

func (x *XferAccepted) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_xfer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XferAccepted.ProtoReflect.Descriptor instead.
func (*XferAccepted) Descriptor() ([]byte, []int) {
	return file_tilder_v1_xfer_proto_rawDescGZIP(), []int{5}
}

func (x *XferAccepted) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type XferProgress struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Bytes     uint64                 `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Total     uint64                 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	Files     uint32                 `protobuf:"varint,4,opt,name=files,proto3" json:"files,omitempty"`
	FilesDone uint32                 `protobuf:"varint,5,opt,name=files_done,json=filesDone,proto3" json:"files_done,omitempty"`
	Route     XferRoute              `protobuf:"varint,6,opt,name=route,proto3,enum=tilder.v1.XferRoute" json:"route,omitempty"`
	// The name copied, as the destination shows it.
	Name []byte `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	// Waiting for the source machine (offline, or the connection being made).
	Waiting bool `protobuf:"varint,8,opt,name=waiting,proto3" json:"waiting,omitempty"`
	// In a List: the copy ended, done when code is unspecified.
	Ended         bool            `protobuf:"varint,9,opt,name=ended,proto3" json:"ended,omitempty"`
	Code          XferFailed_Code `protobuf:"varint,10,opt,name=code,proto3,enum=tilder.v1.XferFailed_Code" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XferProgress) Reset() {
	*x = XferProgress{}
	mi := &file_tilder_v1_xfer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XferProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XferProgress) ProtoMessage() {}

func (x *XferProgress) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_xfer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XferProgress.ProtoReflect.Descriptor instead.
func (*XferProgress) Descriptor() ([]byte, []int) {
	return file_tilder_v1_xfer_proto_rawDescGZIP(), []int{6}
}

func (x *XferProgress) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *XferProgress) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *XferProgress) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *XferProgress) GetFiles() uint32 {
	if x != nil {
		return x.Files
	}
	return 0
}

func (x *XferProgress) GetFilesDone() uint32 {
	if x != nil {
		return x.FilesDone
	}
	return 0
}

func (x *XferProgress) GetRoute() XferRoute {
	if x != nil {
		return x.Route
	}
	return XferRoute_XFER_ROUTE_UNSPECIFIED
}

func (x *XferProgress) GetName() []byte {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *XferProgress) GetWaiting() bool {
	if x != nil {
		return x.Waiting
	}
	return false
}

func (x *XferProgress) GetEnded() bool {
	if x != nil {
		return x.Ended
	}
	return false
}

func (x *XferProgress) GetCode() XferFailed_Code {
	if x != nil {
		return x.Code
	}
	return XferFailed_CODE_UNSPECIFIED
}

type XferDone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XferDone) Reset() {
	*x = XferDone{}
	mi := &file_tilder_v1_xfer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XferDone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XferDone) ProtoMessage() {}

func (x *XferDone) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_xfer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XferDone.ProtoReflect.Descriptor instead.
func (*XferDone) Descriptor() ([]byte, []int) {
	return file_tilder_v1_xfer_proto_rawDescGZIP(), []int{7}
}

func (x *XferDone) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type XferFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          XferFailed_Code        `protobuf:"varint,2,opt,name=code,proto3,enum=tilder.v1.XferFailed_Code" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XferFailed) Reset() {
	*x = XferFailed{}
	mi := &file_tilder_v1_xfer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XferFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XferFailed) ProtoMessage() {}

func (x *XferFailed) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_xfer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XferFailed.ProtoReflect.Descriptor instead.
func (*XferFailed) Descriptor() ([]byte, []int) {
	return file_tilder_v1_xfer_proto_rawDescGZIP(), []int{8}
}

func (x *XferFailed) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *XferFailed) GetCode() XferFailed_Code {
	if x != nil {
		return x.Code
	}
	return XferFailed_CODE_UNSPECIFIED
}

type XferJobs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*XferProgress        `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XferJobs) Reset() {
	*x = XferJobs{}
	mi := &file_tilder_v1_xfer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XferJobs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XferJobs) ProtoMessage() {}

func (x *XferJobs) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_xfer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XferJobs.ProtoReflect.Descriptor instead.
func (*XferJobs) Descriptor() ([]byte, []int) {
	return file_tilder_v1_xfer_proto_rawDescGZIP(), []int{9}
}

func (x *XferJobs) GetJobs() []*XferProgress {
	if x != nil {
		return x.Jobs
	}
	return nil
}

type XferClient struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*XferClient_Manifest
	//	*XferClient_Want
	//	*XferClient_Ack
	Msg           isXferClient_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XferClient) Reset() {
	*x = XferClient{}
	mi := &file_tilder_v1_xfer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XferClient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XferClient) ProtoMessage() {}

func (x *XferClient) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_xfer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XferClient.ProtoReflect.Descriptor instead.
func (*XferClient) Descriptor() ([]byte, []int) {
	return file_tilder_v1_xfer_proto_rawDescGZIP(), []int{10}
}

func (x *XferClient) GetMsg() isXferClient_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *XferClient) GetManifest() *XferManifestRequest {
	if x != nil {
		if x, ok := x.Msg.(*XferClient_Manifest); ok {
			return x.Manifest
		}
	}
	return nil
}

func (x *XferClient) GetWant() *XferWant {
	if x != nil {
		if x, ok := x.Msg.(*XferClient_Want); ok {
			return x.Want
		}
	}
	return nil
}

func (x *XferClient) GetAck() *XferAck {
	if x != nil {
		if x, ok := x.Msg.(*XferClient_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isXferClient_Msg interface {
	isXferClient_Msg()
}

type XferClient_Manifest struct {
	Manifest *XferManifestRequest `protobuf:"bytes,1,opt,name=manifest,proto3,oneof"`
}

type XferClient_Want struct {
	Want *XferWant `protobuf:"bytes,2,opt,name=want,proto3,oneof"`
}

type XferClient_Ack struct {
	Ack *XferAck `protobuf:"bytes,3,opt,name=ack,proto3,oneof"`
}

func (*XferClient_Manifest) isXferClient_Msg() {}

func (*XferClient_Want) isXferClient_Msg() {}

func (*XferClient_Ack) isXferClient_Msg() {}

type XferServer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*XferServer_Manifest
	//	*XferServer_Piece
	//	*XferServer_ChunkEnd
	//	*XferServer_Refused
	Msg           isXferServer_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XferServer) Reset() {
	*x = XferServer{}
	mi := &file_tilder_v1_xfer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XferServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XferServer) ProtoMessage() {}

func (x *XferServer) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_xfer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XferServer.ProtoReflect.Descriptor instead.
func (*XferServer) Descriptor() ([]byte, []int) {
	return file_tilder_v1_xfer_proto_rawDescGZIP(), []int{11}
}

func (x *XferServer) GetMsg() isXferServer_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *XferServer) GetManifest() *XferManifest {
	if x != nil {
		if x, ok := x.Msg.(*XferServer_Manifest); ok {
			return x.Manifest
		}
	}
	return nil
}

func (x *XferServer) GetPiece() *XferPiece {
	if x != nil {
		if x, ok := x.Msg.(*XferServer_Piece); ok {
			return x.Piece
		}
	}
	return nil
}

func (x *XferServer) GetChunkEnd() *XferChunkEnd {
	if x != nil {
		if x, ok := x.Msg.(*XferServer_ChunkEnd); ok {
			return x.ChunkEnd
		}
	}
	return nil
}

func (x *XferServer) GetRefused() *XferRefused {
	if x != nil {
		if x, ok := x.Msg.(*XferServer_Refused); ok {
			return x.Refused
		}
	}
	return nil
}

type isXferServer_Msg interface {
	isXferServer_Msg()
}

type XferServer_Manifest struct {
	Manifest *XferManifest `protobuf:"bytes,1,opt,name=manifest,proto3,oneof"`
}

type XferServer_Piece struct {
	Piece *XferPiece `protobuf:"bytes,2,opt,name=piece,proto3,oneof"`
}

type XferServer_ChunkEnd struct {
	ChunkEnd *XferChunkEnd `protobuf:"bytes,3,opt,name=chunk_end,json=chunkEnd,proto3,oneof"`
}

type XferServer_Refused struct {
	Refused *XferRefused `protobuf:"bytes,4,opt,name=refused,proto3,oneof"`
}

func (*XferServer_Manifest) isXferServer_Msg() {}

func (*XferServer_Piece) isXferServer_Msg() {}

func (*XferServer_ChunkEnd) isXferServer_Msg() {}

func (*XferServer_Refused) isXferServer_Msg() {}

// What the grant names: send its manifest.
type XferManifestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XferManifestRequest) Reset() {
	*x = XferManifestRequest{}
	mi := &file_tilder_v1_xfer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XferManifestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XferManifestRequest) ProtoMessage() {}

func (x *XferManifestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_xfer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XferManifestRequest.ProtoReflect.Descriptor instead.
func (*XferManifestRequest) Descriptor() ([]byte, []int) {
	return file_tilder_v1_xfer_proto_rawDescGZIP(), []int{12}
}

// The manifest comes as pages, each under 16 KiB, in order; `last` ends it.
// Entries are numbered across pages from 0: that number is what Want names.
// A directory comes before what it holds.
type XferManifest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Entries   []*XferEntry           `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	ChunkSize uint32                 `protobuf:"varint,2,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	Last      bool                   `protobuf:"varint,3,opt,name=last,proto3" json:"last,omitempty"`
	// Special files (FIFOs, devices, sockets) left out.
	Skipped       uint32 `protobuf:"varint,4,opt,name=skipped,proto3" json:"skipped,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XferManifest) Reset() {
	*x = XferManifest{}
	mi := &file_tilder_v1_xfer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XferManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XferManifest) ProtoMessage() {}

func (x *XferManifest) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_xfer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XferManifest.ProtoReflect.Descriptor instead.
func (*XferManifest) Descriptor() ([]byte, []int) {
	return file_tilder_v1_xfer_proto_rawDescGZIP(), []int{13}
}

func (x *XferManifest) GetEntries() []*XferEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *XferManifest) GetChunkSize() uint32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *XferManifest) GetLast() bool {
	if x != nil {
		return x.Last
	}
	return false
}

func (x *XferManifest) GetSkipped() uint32 {
	if x != nil {
		return x.Skipped
	}
	return 0
}

// One entry of what is copied: path relative to the grant's source (empty
// for the source itself when it is a file), and how to recreate it.
type XferEntry struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Path    []byte                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Kind    FsKind                 `protobuf:"varint,2,opt,name=kind,proto3,enum=tilder.v1.FsKind" json:"kind,omitempty"`
	Size    uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Perm    uint32                 `protobuf:"varint,4,opt,name=perm,proto3" json:"perm,omitempty"`
	MtimeNs int64                  `protobuf:"varint,5,opt,name=mtime_ns,json=mtimeNs,proto3" json:"mtime_ns,omitempty"`
	// The file as it was listed: a read that finds another version is refused.
	Etag []byte `protobuf:"bytes,6,opt,name=etag,proto3" json:"etag,omitempty"`
	// For a symlink: its target, copied as a link, never followed.
	LinkTarget    []byte `protobuf:"bytes,7,opt,name=link_target,json=linkTarget,proto3" json:"link_target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XferEntry) Reset() {
	*x = XferEntry{}
	mi := &file_tilder_v1_xfer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XferEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XferEntry) ProtoMessage() {}

func (x *XferEntry) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_xfer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XferEntry.ProtoReflect.Descriptor instead.
func (*XferEntry) Descriptor() ([]byte, []int) {
	return file_tilder_v1_xfer_proto_rawDescGZIP(), []int{14}
}

func (x *XferEntry) GetPath() []byte {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *XferEntry) GetKind() FsKind {
	if x != nil {
		return x.Kind
	}
	return FsKind_FS_KIND_UNSPECIFIED
}

func (x *XferEntry) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *XferEntry) GetPerm() uint32 {
	if x != nil {
		return x.Perm
	}
	return 0
}

func (x *XferEntry) GetMtimeNs() int64 {
	if x != nil {
		return x.MtimeNs
	}
	return 0
}

func (x *XferEntry) GetEtag() []byte {
	if x != nil {
		return x.Etag
	}
	return nil
}

func (x *XferEntry) GetLinkTarget() []byte {
	if x != nil {
		return x.LinkTarget
	}
	return nil
}

// Send file `file` (its index in this connection's manifest) from chunk
// `from_chunk` to its end. Wants are served in the order sent. The
// destination never names a path: only what the source listed is served.
type XferWant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          uint32                 `protobuf:"varint,1,opt,name=file,proto3" json:"file,omitempty"`
	FromChunk     uint64                 `protobuf:"varint,2,opt,name=from_chunk,json=fromChunk,proto3" json:"from_chunk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XferWant) Reset() {
	*x = XferWant{}
	mi := &file_tilder_v1_xfer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XferWant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XferWant) ProtoMessage() {}

func (x *XferWant) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_xfer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XferWant.ProtoReflect.Descriptor instead.
func (*XferWant) Descriptor() ([]byte, []int) {
	return file_tilder_v1_xfer_proto_rawDescGZIP(), []int{15}
}

func (x *XferWant) GetFile() uint32 {
	if x != nil {
		return x.File
	}
	return 0
}

func (x *XferWant) GetFromChunk() uint64 {
	if x != nil {
		return x.FromChunk
	}
	return 0
}

// Chunk `index` of file `file` is written and checked: the source may send
// that much more (credit: at most 16 MiB not yet acked).
type XferAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          uint32                 `protobuf:"varint,1,opt,name=file,proto3" json:"file,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XferAck) Reset() {
	*x = XferAck{}
	mi := &file_tilder_v1_xfer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XferAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XferAck) ProtoMessage() {}

func (x *XferAck) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_xfer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XferAck.ProtoReflect.Descriptor instead.
func (*XferAck) Descriptor() ([]byte, []int) {
	return file_tilder_v1_xfer_proto_rawDescGZIP(), []int{16}
}

func (x *XferAck) GetFile() uint32 {
	if x != nil {
		return x.File
	}
	return 0
}

func (x *XferAck) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type XferPiece struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          uint32                 `protobuf:"varint,1,opt,name=file,proto3" json:"file,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XferPiece) Reset() {
	*x = XferPiece{}
	mi := &file_tilder_v1_xfer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XferPiece) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XferPiece) ProtoMessage() {}

func (x *XferPiece) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_xfer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XferPiece.ProtoReflect.Descriptor instead.
func (*XferPiece) Descriptor() ([]byte, []int) {
	return file_tilder_v1_xfer_proto_rawDescGZIP(), []int{17}
}

func (x *XferPiece) GetFile() uint32 {
	if x != nil {
		return x.File
	}
	return 0
}

func (x *XferPiece) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *XferPiece) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// The chunk is complete; its SHA-256, which the destination checks before
// keeping it.
type XferChunkEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	File          uint32                 `protobuf:"varint,1,opt,name=file,proto3" json:"file,omitempty"`
	Index         uint64                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	Sha256        []byte                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XferChunkEnd) Reset() {
	*x = XferChunkEnd{}
	mi := &file_tilder_v1_xfer_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XferChunkEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XferChunkEnd) ProtoMessage() {}

func (x *XferChunkEnd) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_xfer_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XferChunkEnd.ProtoReflect.Descriptor instead.
func (*XferChunkEnd) Descriptor() ([]byte, []int) {
	return file_tilder_v1_xfer_proto_rawDescGZIP(), []int{18}
}

func (x *XferChunkEnd) GetFile() uint32 {
	if x != nil {
		return x.File
	}
	return 0
}

func (x *XferChunkEnd) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *XferChunkEnd) GetSha256() []byte {
	if x != nil {
		return x.Sha256
	}
	return nil
}

// The source will not serve: the whole copy, or, when `file` is set, that one
// file (it changed since the manifest, or is gone), the connection going on.
type XferRefused struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          XferFailed_Code        `protobuf:"varint,1,opt,name=code,proto3,enum=tilder.v1.XferFailed_Code" json:"code,omitempty"`
	File          *uint32                `protobuf:"varint,2,opt,name=file,proto3,oneof" json:"file,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XferRefused) Reset() {
	*x = XferRefused{}
	mi := &file_tilder_v1_xfer_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XferRefused) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XferRefused) ProtoMessage() {}

func (x *XferRefused) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_xfer_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XferRefused.ProtoReflect.Descriptor instead.
func (*XferRefused) Descriptor() ([]byte, []int) {
	return file_tilder_v1_xfer_proto_rawDescGZIP(), []int{19}
}

func (x *XferRefused) GetCode() XferFailed_Code {
	if x != nil {
		return x.Code
	}
	return XferFailed_CODE_UNSPECIFIED
}

func (x *XferRefused) GetFile() uint32 {
	if x != nil && x.File != nil {
		return *x.File
	}
	return 0
}

// `xfer-lan` (ADR 0039): when the connection between the two machines runs
// host to host inside one LAN, the destination opens this channel on it and
// the source answers with one XferLan. The copy's `xfer` messages then go
// over TCP to that port, under TLS with a certificate the source made for
// this one offer, each message behind a 4-byte length. The destination pins
// `cert_sha256` and sends `token` as its first message; both came over the
// connection the grant opened, so no one else holds them. The channel stays
// open while the copy runs: when it closes, so does the TCP connection.
// Anything else and the copy stays on the `xfer` channel.
type XferLan struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Port  uint32                 `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	// SHA-256 of the certificate's DER.
	CertSha256 []byte `protobuf:"bytes,2,opt,name=cert_sha256,json=certSha256,proto3" json:"cert_sha256,omitempty"`
	// 32 random bytes, for one connection.
	Token         []byte `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XferLan) Reset() {
	*x = XferLan{}
	mi := &file_tilder_v1_xfer_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XferLan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XferLan) ProtoMessage() {}

func (x *XferLan) ProtoReflect() protoreflect.Message {
	mi := &file_tilder_v1_xfer_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XferLan.ProtoReflect.Descriptor instead.
func (*XferLan) Descriptor() ([]byte, []int) {
	return file_tilder_v1_xfer_proto_rawDescGZIP(), []int{20}
}

func (x *XferLan) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *XferLan) GetCertSha256() []byte {
	if x != nil {
		return x.CertSha256
	}
	return nil
}

func (x *XferLan) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

var File_tilder_v1_xfer_proto protoreflect.FileDescriptor

const file_tilder_v1_xfer_proto_rawDesc = "" +
	"\n" +
	"\x14tilder/v1/xfer.proto\x12\ttilder.v1\x1a\x12tilder/v1/fs.proto\x1a\x1atilder/v1/rendezvous.proto\"\xb4\x01\n" +
	"\rXferCtlClient\x12\x15\n" +
	"\x06req_id\x18\x01 \x01(\rR\x05reqId\x12)\n" +
	"\x04pull\x18\x02 \x01(\v2\x13.tilder.v1.XferPullH\x00R\x04pull\x12)\n" +
	"\x04list\x18\x03 \x01(\v2\x13.tilder.v1.XferListH\x00R\x04list\x12/\n" +
	"\x06cancel\x18\x04 \x01(\v2\x15.tilder.v1.XferCancelH\x00R\x06cancelB\x05\n" +
	"\x03msg\"\xa2\x02\n" +
	"\rXferCtlServer\x12\x15\n" +
	"\x06req_id\x18\x01 \x01(\rR\x05reqId\x125\n" +
	"\baccepted\x18\x02 \x01(\v2\x17.tilder.v1.XferAcceptedH\x00R\baccepted\x125\n" +
	"\bprogress\x18\x03 \x01(\v2\x17.tilder.v1.XferProgressH\x00R\bprogress\x12)\n" +
	"\x04done\x18\x04 \x01(\v2\x13.tilder.v1.XferDoneH\x00R\x04done\x12/\n" +
	"\x06failed\x18\x05 \x01(\v2\x15.tilder.v1.XferFailedH\x00R\x06failed\x12)\n" +
	"\x04jobs\x18\x06 \x01(\v2\x13.tilder.v1.XferJobsH\x00R\x04jobsB\x05\n" +
	"\x03msg\":\n" +
	"\bXferPull\x12.\n" +
	"\x05grant\x18\x01 \x01(\v2\x18.tilder.v1.TransferGrantR\x05grant\"\n" +
	"\n" +
	"\bXferList\"\x1c\n" +
	"\n" +
	"XferCancel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1e\n" +
	"\fXferAccepted\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9f\x02\n" +
	"\fXferProgress\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\x04R\x05bytes\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x04R\x05total\x12\x14\n" +
	"\x05files\x18\x04 \x01(\rR\x05files\x12\x1d\n" +
	"\n" +
	"files_done\x18\x05 \x01(\rR\tfilesDone\x12*\n" +
	"\x05route\x18\x06 \x01(\x0e2\x14.tilder.v1.XferRouteR\x05route\x12\x12\n" +
	"\x04name\x18\a \x01(\fR\x04name\x12\x18\n" +
	"\awaiting\x18\b \x01(\bR\awaiting\x12\x14\n" +
	"\x05ended\x18\t \x01(\bR\x05ended\x12.\n" +
	"\x04code\x18\n" +
	" \x01(\x0e2\x1a.tilder.v1.XferFailed.CodeR\x04code\"\x1a\n" +
	"\bXferDone\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x98\x02\n" +
	"\n" +
	"XferFailed\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12.\n" +
	"\x04code\x18\x02 \x01(\x0e2\x1a.tilder.v1.XferFailed.CodeR\x04code\"\xc9\x01\n" +
	"\x04Code\x12\x14\n" +
	"\x10CODE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vCODE_DENIED\x10\x01\x12\x14\n" +
	"\x10CODE_UNREACHABLE\x10\x02\x12\x12\n" +
	"\x0eCODE_NOT_FOUND\x10\x03\x12\x11\n" +
	"\rCODE_NO_SPACE\x10\x04\x12\x10\n" +
	"\fCODE_CHANGED\x10\x05\x12\x12\n" +
	"\x0eCODE_CANCELLED\x10\x06\x12\x10\n" +
	"\fCODE_EXPIRED\x10\a\x12\x11\n" +
	"\rCODE_INTERNAL\x10\b\x12\x12\n" +
	"\x0eCODE_TOO_LARGE\x10\t\"7\n" +
	"\bXferJobs\x12+\n" +
	"\x04jobs\x18\x01 \x03(\v2\x17.tilder.v1.XferProgressR\x04jobs\"\xa4\x01\n" +
	"\n" +
	"XferClient\x12<\n" +
	"\bmanifest\x18\x01 \x01(\v2\x1e.tilder.v1.XferManifestRequestH\x00R\bmanifest\x12)\n" +
	"\x04want\x18\x02 \x01(\v2\x13.tilder.v1.XferWantH\x00R\x04want\x12&\n" +
	"\x03ack\x18\x03 \x01(\v2\x12.tilder.v1.XferAckH\x00R\x03ackB\x05\n" +
	"\x03msg\"\xe4\x01\n" +
	"\n" +
	"XferServer\x125\n" +
	"\bmanifest\x18\x01 \x01(\v2\x17.tilder.v1.XferManifestH\x00R\bmanifest\x12,\n" +
	"\x05piece\x18\x02 \x01(\v2\x14.tilder.v1.XferPieceH\x00R\x05piece\x126\n" +
	"\tchunk_end\x18\x03 \x01(\v2\x17.tilder.v1.XferChunkEndH\x00R\bchunkEnd\x122\n" +
	"\arefused\x18\x04 \x01(\v2\x16.tilder.v1.XferRefusedH\x00R\arefusedB\x05\n" +
	"\x03msg\"\x15\n" +
	"\x13XferManifestRequest\"\x8b\x01\n" +
	"\fXferManifest\x12.\n" +
	"\aentries\x18\x01 \x03(\v2\x14.tilder.v1.XferEntryR\aentries\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x02 \x01(\rR\tchunkSize\x12\x12\n" +
	"\x04last\x18\x03 \x01(\bR\x04last\x12\x18\n" +
	"\askipped\x18\x04 \x01(\rR\askipped\"\xbe\x01\n" +
	"\tXferEntry\x12\x12\n" +
	"\x04path\x18\x01 \x01(\fR\x04path\x12%\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x11.tilder.v1.FsKindR\x04kind\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\x12\x12\n" +
	"\x04perm\x18\x04 \x01(\rR\x04perm\x12\x19\n" +
	"\bmtime_ns\x18\x05 \x01(\x03R\amtimeNs\x12\x12\n" +
	"\x04etag\x18\x06 \x01(\fR\x04etag\x12\x1f\n" +
	"\vlink_target\x18\a \x01(\fR\n" +
	"linkTarget\"=\n" +
	"\bXferWant\x12\x12\n" +
	"\x04file\x18\x01 \x01(\rR\x04file\x12\x1d\n" +
	"\n" +
	"from_chunk\x18\x02 \x01(\x04R\tfromChunk\"3\n" +
	"\aXferAck\x12\x12\n" +
	"\x04file\x18\x01 \x01(\rR\x04file\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\"I\n" +
	"\tXferPiece\x12\x12\n" +
	"\x04file\x18\x01 \x01(\rR\x04file\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"P\n" +
	"\fXferChunkEnd\x12\x12\n" +
	"\x04file\x18\x01 \x01(\rR\x04file\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x04R\x05index\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\fR\x06sha256\"_\n" +
	"\vXferRefused\x12.\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1a.tilder.v1.XferFailed.CodeR\x04code\x12\x17\n" +
	"\x04file\x18\x02 \x01(\rH\x00R\x04file\x88\x01\x01B\a\n" +
	"\x05_file\"T\n" +
	"\aXferLan\x12\x12\n" +
	"\x04port\x18\x01 \x01(\rR\x04port\x12\x1f\n" +
	"\vcert_sha256\x18\x02 \x01(\fR\n" +
	"certSha256\x12\x14\n" +
	"\x05token\x18\x03 \x01(\fR\x05token*V\n" +
	"\tXferRoute\x12\x1a\n" +
	"\x16XFER_ROUTE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11XFER_ROUTE_DIRECT\x10\x01\x12\x16\n" +
	"\x12XFER_ROUTE_RELAYED\x10\x02B?Z=github.com/nghyane/tilder/go/internal/wire/tilder/v1;tilderv1b\x06proto3"

var (
	file_tilder_v1_xfer_proto_rawDescOnce sync.Once
	file_tilder_v1_xfer_proto_rawDescData []byte
)

func file_tilder_v1_xfer_proto_rawDescGZIP() []byte {
	file_tilder_v1_xfer_proto_rawDescOnce.Do(func() {
		file_tilder_v1_xfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tilder_v1_xfer_proto_rawDesc), len(file_tilder_v1_xfer_proto_rawDesc)))
	})
	return file_tilder_v1_xfer_proto_rawDescData
}

var file_tilder_v1_xfer_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tilder_v1_xfer_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_tilder_v1_xfer_proto_goTypes = []any{
	(XferRoute)(0),              // 0: tilder.v1.XferRoute
	(XferFailed_Code)(0),        // 1: tilder.v1.XferFailed.Code
	(*XferCtlClient)(nil),       // 2: tilder.v1.XferCtlClient
	(*XferCtlServer)(nil),       // 3: tilder.v1.XferCtlServer
	(*XferPull)(nil),            // 4: tilder.v1.XferPull
	(*XferList)(nil),            // 5: tilder.v1.XferList
	(*XferCancel)(nil),          // 6: tilder.v1.XferCancel
	(*XferAccepted)(nil),        // 7: tilder.v1.XferAccepted
	(*XferProgress)(nil),        // 8: tilder.v1.XferProgress
	(*XferDone)(nil),            // 9: tilder.v1.XferDone
	(*XferFailed)(nil),          // 10: tilder.v1.XferFailed
	(*XferJobs)(nil),            // 11: tilder.v1.XferJobs
	(*XferClient)(nil),          // 12: tilder.v1.XferClient
	(*XferServer)(nil),          // 13: tilder.v1.XferServer
	(*XferManifestRequest)(nil), // 14: tilder.v1.XferManifestRequest
	(*XferManifest)(nil),        // 15: tilder.v1.XferManifest
	(*XferEntry)(nil),           // 16: tilder.v1.XferEntry
	(*XferWant)(nil),            // 17: tilder.v1.XferWant
	(*XferAck)(nil),             // 18: tilder.v1.XferAck
	(*XferPiece)(nil),           // 19: tilder.v1.XferPiece
	(*XferChunkEnd)(nil),        // 20: tilder.v1.XferChunkEnd
	(*XferRefused)(nil),         // 21: tilder.v1.XferRefused
	(*XferLan)(nil),             // 22: tilder.v1.XferLan
	(*TransferGrant)(nil),       // 23: tilder.v1.TransferGrant
	(FsKind)(0),                 // 24: tilder.v1.FsKind
}
var file_tilder_v1_xfer_proto_depIdxs = []int32{
	4,  // 0: tilder.v1.XferCtlClient.pull:type_name -> tilder.v1.XferPull
	5,  // 1: tilder.v1.XferCtlClient.list:type_name -> tilder.v1.XferList
	6,  // 2: tilder.v1.XferCtlClient.cancel:type_name -> tilder.v1.XferCancel
	7,  // 3: tilder.v1.XferCtlServer.accepted:type_name -> tilder.v1.XferAccepted
	8,  // 4: tilder.v1.XferCtlServer.progress:type_name -> tilder.v1.XferProgress
	9,  // 5: tilder.v1.XferCtlServer.done:type_name -> tilder.v1.XferDone
	10, // 6: tilder.v1.XferCtlServer.failed:type_name -> tilder.v1.XferFailed
	11, // 7: tilder.v1.XferCtlServer.jobs:type_name -> tilder.v1.XferJobs
	23, // 8: tilder.v1.XferPull.grant:type_name -> tilder.v1.TransferGrant
	0,  // 9: tilder.v1.XferProgress.route:type_name -> tilder.v1.XferRoute
	1,  // 10: tilder.v1.XferProgress.code:type_name -> tilder.v1.XferFailed.Code
	1,  // 11: tilder.v1.XferFailed.code:type_name -> tilder.v1.XferFailed.Code
	8,  // 12: tilder.v1.XferJobs.jobs:type_name -> tilder.v1.XferProgress
	14, // 13: tilder.v1.XferClient.manifest:type_name -> tilder.v1.XferManifestRequest
	17, // 14: tilder.v1.XferClient.want:type_name -> tilder.v1.XferWant
	18, // 15: tilder.v1.XferClient.ack:type_name -> tilder.v1.XferAck
	15, // 16: tilder.v1.XferServer.manifest:type_name -> tilder.v1.XferManifest
	19, // 17: tilder.v1.XferServer.piece:type_name -> tilder.v1.XferPiece
	20, // 18: tilder.v1.XferServer.chunk_end:type_name -> tilder.v1.XferChunkEnd
	21, // 19: tilder.v1.XferServer.refused:type_name -> tilder.v1.XferRefused
	16, // 20: tilder.v1.XferManifest.entries:type_name -> tilder.v1.XferEntry
	24, // 21: tilder.v1.XferEntry.kind:type_name -> tilder.v1.FsKind
	1,  // 22: tilder.v1.XferRefused.code:type_name -> tilder.v1.XferFailed.Code
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_tilder_v1_xfer_proto_init() }
func file_tilder_v1_xfer_proto_init() {
	if File_tilder_v1_xfer_proto != nil {
		return
	}
	file_tilder_v1_fs_proto_init()
	file_tilder_v1_rendezvous_proto_init()
	file_tilder_v1_xfer_proto_msgTypes[0].OneofWrappers = []any{
		(*XferCtlClient_Pull)(nil),
		(*XferCtlClient_List)(nil),
		(*XferCtlClient_Cancel)(nil),
	}
	file_tilder_v1_xfer_proto_msgTypes[1].OneofWrappers = []any{
		(*XferCtlServer_Accepted)(nil),
		(*XferCtlServer_Progress)(nil),
		(*XferCtlServer_Done)(nil),
		(*XferCtlServer_Failed)(nil),
		(*XferCtlServer_Jobs)(nil),
	}
	file_tilder_v1_xfer_proto_msgTypes[10].OneofWrappers = []any{
		(*XferClient_Manifest)(nil),
		(*XferClient_Want)(nil),
		(*XferClient_Ack)(nil),
	}
	file_tilder_v1_xfer_proto_msgTypes[11].OneofWrappers = []any{
		(*XferServer_Manifest)(nil),
		(*XferServer_Piece)(nil),
		(*XferServer_ChunkEnd)(nil),
		(*XferServer_Refused)(nil),
	}
	file_tilder_v1_xfer_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tilder_v1_xfer_proto_rawDesc), len(file_tilder_v1_xfer_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tilder_v1_xfer_proto_goTypes,
		DependencyIndexes: file_tilder_v1_xfer_proto_depIdxs,
		EnumInfos:         file_tilder_v1_xfer_proto_enumTypes,
		MessageInfos:      file_tilder_v1_xfer_proto_msgTypes,
	}.Build()
	File_tilder_v1_xfer_proto = out.File
	file_tilder_v1_xfer_proto_goTypes = nil
	file_tilder_v1_xfer_proto_depIdxs = nil
}
